/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './commercial-license-oem.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './legal.component.css.shim';
import * as import9 from '../common/header/header.component';
import * as import10 from '../common/header/header.component.ngfactory';
import * as import11 from './legal-menu.component';
import * as import12 from './legal-menu.component.ngfactory';
export class Wrapper_CommercialLicenseOemComponent {
  /*private*/ _eventHandler:Function;
  context:import0.CommercialLicenseOemComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.CommercialLicenseOemComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_CommercialLicenseOemComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_CommercialLicenseOemComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.CommercialLicenseOemComponent>;
  _CommercialLicenseOemComponent_0_3:Wrapper_CommercialLicenseOemComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CommercialLicenseOemComponent_Host0,renderType_CommercialLicenseOemComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_CommercialLicenseOemComponent0(this.viewUtils,this,0,this._el_0);
    this._CommercialLicenseOemComponent_0_3 = new Wrapper_CommercialLicenseOemComponent();
    this.compView_0.create(this._CommercialLicenseOemComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._CommercialLicenseOemComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.CommercialLicenseOemComponent) && (0 === requestNodeIndex))) { return this._CommercialLicenseOemComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CommercialLicenseOemComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const CommercialLicenseOemComponentNgFactory:import7.ComponentFactory<import0.CommercialLicenseOemComponent> = new import7.ComponentFactory<import0.CommercialLicenseOemComponent>('ng-component',View_CommercialLicenseOemComponent_Host0,import0.CommercialLicenseOemComponent);
const styles_CommercialLicenseOemComponent:any[] = [import8.styles];
var renderType_CommercialLicenseOemComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_CommercialLicenseOemComponent,{});
export class View_CommercialLicenseOemComponent0 extends import1.AppView<import0.CommercialLicenseOemComponent> {
  _el_0:any;
  compView_0:import1.AppView<import9.HeaderComponent>;
  _HeaderComponent_0_3:import10.Wrapper_HeaderComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import11.LegalMenuComponent>;
  _LegalMenuComponent_4_3:import12.Wrapper_LegalMenuComponent;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _text_82:any;
  _el_83:any;
  _text_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _text_100:any;
  _text_101:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CommercialLicenseOemComponent0,renderType_CommercialLicenseOemComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'pm-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import10.View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new import10.Wrapper_HeaderComponent();
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'legalMenu',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_4 = new import12.View_LegalMenuComponent0(this.viewUtils,this,4,this._el_4);
    this._LegalMenuComponent_4_3 = new import12.Wrapper_LegalMenuComponent();
    this.compView_4.create(this._LegalMenuComponent_4_3.context);
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','body'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Extension to the slamby api commercial license for royalty free distribution (oem)',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'1. Definitions',(null as any));
    this._text_13 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'When used in this Agreement, the following terms shall have the respective meanings indicated, such meanings to be applicable to both the singular and plural forms of the terms defined:',(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_6,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'“We” or “Us” or “Slamby” or “Our” or the “Company” refers to Slamby-Semantics Ltd.',(null as any));
    this._text_21 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_17,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'“You” and “Your” and “User” refers to the entity and/or individual person, natural or legal, consenting to, and entering into, this Agreement.',(null as any));
    this._text_24 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_17,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'"Licensor" means Slamby.',(null as any));
    this._text_27 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_17,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'"Software" means (a) all of the contents of the files, disk(s), disk image(s), Docker containers or other media with which this Agreement is provided, including but not limited to ((i) digital images (ii) related explanatory written materials or files ("Documentation"); and (iii) fonts; and (b) upgrades, modified versions, updates, additions, and copies of the Software, if any, licensed to you by Slamby (collectively, "Updates").',(null as any));
    this._text_30 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_17,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'"Use" or "Using" means to access, install, download, copy or otherwise benefit from using the functionality of the Software.',(null as any));
    this._text_33 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_17,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'"Licensee" means You or Your Company, unless otherwise indicated.',(null as any));
    this._text_36 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_17,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'"System" means Windows OS, GNU/Linux or Mac OS X, Docker or any virtual machine.',(null as any));
    this._text_39 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._text_40 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'2. General Use',(null as any));
    this._text_43 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'As long as the Licensee complies with the terms of this extension of End User License Agreement (the "Agreement") and the Agreement itself, the Licensor grants the Licensee a non-exclusive right to install and Use the Software for the purposes described in the Documentation under the following conditions:',(null as any));
    this._text_46 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'The Software may be installed and used by the Licensee for business, commercial and money-earning purposes.',(null as any));
    this._text_49 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'This License can be deployed on any number of systems.',(null as any));
    this._text_52 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'The Software under this License may be incorporated into software/hardware projects sold by the Licensee.',(null as any));
    this._text_55 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'The Licensee may physically or electronically distribute the Software to his manufacturing and service partners but only as an intermediary product, requiring incorporation of the Software into the software or hardware developed by the Licensee in cases when the manufacturing process involves the Licensee\'s partner\'s job to complete the project before distributing it to end-users.',(null as any));
    this._text_58 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'The Licensee or his manufacturing and service partners may reproduce and physically or electronically distribute the Software only as an integral part of or incorporated into their software or hardware product.',(null as any));
    this._text_61 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'This License entitles the Licensee to the unlimited redistribution of the Licensor\'s technology as a part of the Licensee\'s product.',(null as any));
    this._text_64 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'This License is royalty-free, i.e. the Licensee does not need to pay a fee per every order of his product with the incorporated Licensor\'s technology.',(null as any));
    this._text_67 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'This License cannot be used by the Licensee to develop a software application that would compete with products marketed by the Licensor.',(null as any));
    this._text_70 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'3. Intellectual Property Rights',(null as any));
    this._text_73 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'3.1 This License does not transmit any intellectual rights on the Software. The Software and any copies that the Licensee is authorized by the Licensor to make are the intellectual property of and are owned by the Licensor.',(null as any));
    this._text_76 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_78 = this.renderer.createText(this._el_77,'3.2 The Software is protected by copyright, including without limitation by Copyright Law and international treaty provisions.',(null as any));
    this._text_79 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_80 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_81 = this.renderer.createText(this._el_80,'3.3 Any copies that the Licensee is permitted to make pursuant to this Agreement must contain the same copyright and other proprietary notices that appear on or in the Software.',(null as any));
    this._text_82 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_83 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_84 = this.renderer.createText(this._el_83,'3.4 Any information supplied by the Licensor or obtained by the Licensee, as permitted hereunder, may only be used by the Licensee for the purpose described herein and may not be disclosed to any third party or used to create any software which is substantially similar to the expression of the Software.',(null as any));
    this._text_85 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_87 = this.renderer.createText(this._el_86,'3.5 Trademarks shall be used in accordance with accepted trademark practice, including identification of trademarks owners\' names. Trademarks can only be used to identify printed output produced by the Software and such use of any trademark does not give the Licensee any rights of ownership in that trademark.',(null as any));
    this._text_88 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_89 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'License Transfer',(null as any));
    this._text_91 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_92 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_93 = this.renderer.createText(this._el_92,'4.1 This License is non-transferable. The Licensee may not transfer the rights to Use the Software to third parties (another person or legal entity).',(null as any));
    this._text_94 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_95 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_96 = this.renderer.createText(this._el_95,'4.2 The Licensee may not rent, lease, sub-license, lend or transfer any versions or copies of the Software to third parties (another person or legal entity).',(null as any));
    this._text_97 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_98 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_99 = this.renderer.createText(this._el_98,'4.3 The Licensee may make a back-up copy of the Software, provided a backup copy is not installed or used on any system not belonging to the Licensee. The Licensee may not transfer the rights to install or use a backup copy of the Software to third parties (another person or legal entity).',(null as any));
    this._text_100 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_101 = this.renderer.createText(this._el_2,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._text_100,
      this._text_101
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    if (((token === import11.LegalMenuComponent) && (4 === requestNodeIndex))) { return this._LegalMenuComponent_4_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._LegalMenuComponent_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
    this.compView_4.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this.compView_4.destroy();
  }
}