/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './commercial-license.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './legal.component.css.shim';
import * as import9 from '../common/header/header.component';
import * as import10 from '../common/header/header.component.ngfactory';
import * as import11 from './legal-menu.component';
import * as import12 from './legal-menu.component.ngfactory';
export class Wrapper_CommercialLicenseComponent {
  /*private*/ _eventHandler:Function;
  context:import0.CommercialLicenseComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.CommercialLicenseComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_CommercialLicenseComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_CommercialLicenseComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.CommercialLicenseComponent>;
  _CommercialLicenseComponent_0_3:Wrapper_CommercialLicenseComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CommercialLicenseComponent_Host0,renderType_CommercialLicenseComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_CommercialLicenseComponent0(this.viewUtils,this,0,this._el_0);
    this._CommercialLicenseComponent_0_3 = new Wrapper_CommercialLicenseComponent();
    this.compView_0.create(this._CommercialLicenseComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._CommercialLicenseComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.CommercialLicenseComponent) && (0 === requestNodeIndex))) { return this._CommercialLicenseComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CommercialLicenseComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const CommercialLicenseComponentNgFactory:import7.ComponentFactory<import0.CommercialLicenseComponent> = new import7.ComponentFactory<import0.CommercialLicenseComponent>('ng-component',View_CommercialLicenseComponent_Host0,import0.CommercialLicenseComponent);
const styles_CommercialLicenseComponent:any[] = [import8.styles];
var renderType_CommercialLicenseComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_CommercialLicenseComponent,{});
export class View_CommercialLicenseComponent0 extends import1.AppView<import0.CommercialLicenseComponent> {
  _el_0:any;
  compView_0:import1.AppView<import9.HeaderComponent>;
  _HeaderComponent_0_3:import10.Wrapper_HeaderComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import11.LegalMenuComponent>;
  _LegalMenuComponent_4_3:import12.Wrapper_LegalMenuComponent;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CommercialLicenseComponent0,renderType_CommercialLicenseComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'pm-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import10.View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new import10.Wrapper_HeaderComponent();
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'legalMenu',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_4 = new import12.View_LegalMenuComponent0(this.viewUtils,this,4,this._el_4);
    this._LegalMenuComponent_4_3 = new import12.Wrapper_LegalMenuComponent();
    this.compView_4.create(this._LegalMenuComponent_4_3.context);
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','body'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'End user license agreement',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_6,'p',new import3.InlineArray2(2,'class','lead'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'You should carefully read the following end user license agreement before installing this software. by installing, copying, or otherwise using the software, you agree to be bound by the terms of this agreement. if you do not agree to the terms of this agreement, please contact slamby at https://www.slamby.com to arrange a full refund.',(null as any));
    this._text_13 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'This software, and any files that are delivered to you by Slamby-Semantics Ltd (referred to herein as “Slamby”). (via on-line transmission or otherwise) to "patch," update, or otherwise modify the software program, as well as any printed materials and any on-line or electronic documentation (the "Manual"), and any and all copies and derivative works of such software program and materials (collectively the "Software") are the copyrighted work of Slamby, or its suppliers and licensors (collectively referred to herein as "Licensor"). All use of the Software is governed by the terms of this End User License Agreement ("License Agreement" or "Agreement"). The Software is distributed solely for use by authorized individuals or entities according to the terms of the License Agreement. Any use, reproduction or redistribution of the Software not expressly authorized by the terms of the License Agreement is expressly prohibited.',(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Ownership',(null as any));
    this._text_19 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'All title, ownership rights and intellectual property rights in and to the Software and all copies thereof (including, but not limited to, any titles, computer code, artwork, any related documentation, executable code, shared libraries, proprietary computer protocols and "applets" incorporated into the Software) are owned or expressly licensed by Licensor. The Software is protected by the copyright laws of Hungary, international copyright treaties and conventions, and other laws. All rights are reserved. The Software may contain certain licensed materials, and the licensors of those materials may enforce their rights in the event of any violation of this License Agreement.',(null as any));
    this._text_22 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Each license purchased for this Software allows once instance of the Software to be used. You may not use multiple instances of the Software without obtaining, in advance, a new license or licenses for the new instance or instances and/or express written permission from Slamby. You may only permanently transfer ownership of the Software and all parts thereof, and all of your rights and obligations under the License Agreement, to another individual or entity, once you have notified Slamby. In this case, Slamby will issue a license for the new individual or entity once it has been established that old instance is no longer in use.',(null as any));
    this._text_25 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'For the specific case of license(s) purchased for redistribution of this Software as part of licensee’s products, no notification to Slamby. shall be required and the license shall automatically transfer so long as the old instance is not in use by the licensee.',(null as any));
    this._text_28 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'Responsibilities of end user',(null as any));
    this._text_31 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'Subject to the Grant of License hereinabove, you may NOT, in whole or in part, copy, photocopy, reproduce, translate, reverse engineer, derive source code, modify, disassemble, decompile, or create derivative works based on the Software, or remove any proprietary notices or labels on the Software, with the exception of the non-compiled source files provided with the Software, including but not limited to template files and script files, which may be modified for use on the user specified in part “Ownership” only. Failure to comply with the restrictions and limitations contained in this Section 2 shall result in immediate, automatic termination of the license granted hereunder and may subject you to civil and/or criminal liability. Notwithstanding the foregoing, you may make one (1) copy of the Software and the Manuals for archival purposes only.',(null as any));
    this._text_34 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'Termination',(null as any));
    this._text_37 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'This License Agreement is effective until terminated. You may terminate the License Agreement at any time by (i) removing the Software from your hard drive, and (ii) notify Licensor of your intention to terminate this License Agreement. Licensor may, at its discretion, terminate this License agreement in the event that you fail to comply with the terms and conditions contained herein. In such event, you must either take immediate action to ensure that you are compliant with this License Agreement or cease all usage of the Software within 30 days from being notified of the termination of License agreement by the Licensor. Upon termination of this Agreement for any reason, all licenses granted herein shall immediately terminate.',(null as any));
    this._text_40 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'Limitation of liability',(null as any));
    this._text_43 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'NEITHER LICENSOR NOR ITS PARENT, SUBSIDIARIES OR AFFILIATES SHALL BE LIABLE IN ANY WAY FOR LOSS OR DAMAGE OF ANY KIND RESULTING FROM THE USE OF THE SOFTWARE, INCLUDING, BUT NOT LIMITED TO, LOSS OF DATA, LOSS OF GOODWILL, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, OR ANY AND ALL OTHER DAMAGES OR LOSSES. FURTHER, LICENSOR SHALL NOT BE LIABLE IN ANY WAY FOR THE LOSS OR DAMAGE TO PRODUCT DATA, LAYOUTS, TEMPLATES, ARTWORK, PRICING, PREDICTION, ANALYSIS AND OTHER INFORMATION STORED BY THE SOFTWARE. LICENSOR SHALL NOT BE RESPONSIBLE FOR ANY INTERRUPTIONS OF SERVICE, INCLUDING, BUT NOT LIMITED TO, ISP DISRUPTIONS, SOFTWARE OR HARDWARE FAILURES OR ANY OTHER EVENT WHICH MAY RESULT IN A LOSS OF DATA OR DISRUPTION OF SERVICE. IN NO EVENT WILL LICENSOR BE LIABLE TO YOU FOR ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES. Some countries and regions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitations may not apply to you.',(null as any));
    this._text_46 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'Equitable remedies',(null as any));
    this._text_49 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'You hereby agree that Licensor would be irreparably damaged if the terms of this License Agreement were not specifically enforced, and therefore you agree that Licensor shall be entitled, without bond, other security, or proof of damages, to appropriate equitable remedies with respect to breaches of this License Agreement, in addition to such other remedies as Licensor may otherwise have available to it under applicable laws. In the event any litigation is brought by either party in connection with this License Agreement, the prevailing party in such litigation shall be entitled to recover from the other party all the costs, attorneys\' fees and other expenses incurred by such prevailing party in the litigation.',(null as any));
    this._text_52 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'Changes to the Agreement',(null as any));
    this._text_55 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'Slamby reserves the right, at its sole discretion, to change, modify, add to, supplement or delete any of the terms and conditions of this License Agreement when Slamby upgrades the Software, effective upon prior notice as follows: Slamby will post notification of any such changes to this License Agreement on the Slamby.com website and will post the revised version of this License Agreement in this location, and may provide such other notice as Slamby may elect in its sole discretion, which may include by email, postal mail or pop-up screen.',(null as any));
    this._text_58 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'If any future changes to this License Agreement are unacceptable to you or cause you to no longer be in compliance with this License Agreement, you may terminate this License Agreement in accordance with Section 3 herein. Your installation and use of any updated or modifications to the Software following notice of changes to this Agreement as described above will mean you accept any and all such changes. You may continue to use your pre-existing installation of the Software under the original License Agreement if you so notify Slamby. within 30 days of the change in the license. Slamby may change, modify, suspend, or discontinue any aspect of the Software at any time. Slamby may also impose limits on certain features or restrict your access to parts or all of the Software without notice or liability. You have no interest, monetary or otherwise, in any feature or content contained in the Software.',(null as any));
    this._text_61 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'Miscellaneous',(null as any));
    this._text_64 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'This License Agreement shall be deemed to have been made and executed in Hungary without regard to conflicts of law provisions, and any dispute arising hereunder shall be resolved in accordance with the law of Hungary. You agree that any claim asserted in any legal proceeding by one of the parties against the other shall be commenced and maintained in Hungary, having subject matter jurisdiction with respect to the dispute between the parties. In the event that any provision of this License Agreement shall be held by a court or other tribunal of competent jurisdiction to be unenforceable, such provision will be enforced to the maximum extent permissible, and the remaining portions of this License Agreement shall remain in full force and effect. This License Agreement constitutes and contains the entire agreement between the parties with respect to the subject matter hereof and supersedes any prior oral or written agreements.',(null as any));
    this._text_67 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'I hereby acknowledge that I have read and understand the foregoing License Agreement and agree that the action of installing the Software is an acknowledgment of my agreement to be bound by the terms and conditions of the License Agreement contained herein.',(null as any));
    this._text_70 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'2013-2016 Slamby-Semantics Ltd. All rights reserved.',(null as any));
    this._text_73 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_74 = this.renderer.createText(this._el_2,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._text_74
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    if (((token === import11.LegalMenuComponent) && (4 === requestNodeIndex))) { return this._LegalMenuComponent_4_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._LegalMenuComponent_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
    this.compView_4.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this.compView_4.destroy();
  }
}