/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './gnu-agpl-license.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './legal.component.css.shim';
import * as import9 from '../common/header/header.component';
import * as import10 from '../common/header/header.component.ngfactory';
import * as import11 from './legal-menu.component';
import * as import12 from './legal-menu.component.ngfactory';
export class Wrapper_GnuAgplLicenseComponent {
  /*private*/ _eventHandler:Function;
  context:import0.GnuAgplLicenseComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.GnuAgplLicenseComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_GnuAgplLicenseComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_GnuAgplLicenseComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.GnuAgplLicenseComponent>;
  _GnuAgplLicenseComponent_0_3:Wrapper_GnuAgplLicenseComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_GnuAgplLicenseComponent_Host0,renderType_GnuAgplLicenseComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_GnuAgplLicenseComponent0(this.viewUtils,this,0,this._el_0);
    this._GnuAgplLicenseComponent_0_3 = new Wrapper_GnuAgplLicenseComponent();
    this.compView_0.create(this._GnuAgplLicenseComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._GnuAgplLicenseComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.GnuAgplLicenseComponent) && (0 === requestNodeIndex))) { return this._GnuAgplLicenseComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._GnuAgplLicenseComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const GnuAgplLicenseComponentNgFactory:import7.ComponentFactory<import0.GnuAgplLicenseComponent> = new import7.ComponentFactory<import0.GnuAgplLicenseComponent>('ng-component',View_GnuAgplLicenseComponent_Host0,import0.GnuAgplLicenseComponent);
const styles_GnuAgplLicenseComponent:any[] = [import8.styles];
var renderType_GnuAgplLicenseComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_GnuAgplLicenseComponent,{});
export class View_GnuAgplLicenseComponent0 extends import1.AppView<import0.GnuAgplLicenseComponent> {
  _el_0:any;
  compView_0:import1.AppView<import9.HeaderComponent>;
  _HeaderComponent_0_3:import10.Wrapper_HeaderComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import11.LegalMenuComponent>;
  _LegalMenuComponent_4_3:import12.Wrapper_LegalMenuComponent;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  _el_83:any;
  _text_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _text_100:any;
  _el_101:any;
  _text_102:any;
  _text_103:any;
  _el_104:any;
  _el_105:any;
  _text_106:any;
  _text_107:any;
  _el_108:any;
  _text_109:any;
  _text_110:any;
  _el_111:any;
  _text_112:any;
  _text_113:any;
  _el_114:any;
  _text_115:any;
  _text_116:any;
  _el_117:any;
  _el_118:any;
  _text_119:any;
  _text_120:any;
  _el_121:any;
  _text_122:any;
  _text_123:any;
  _el_124:any;
  _text_125:any;
  _text_126:any;
  _el_127:any;
  _el_128:any;
  _text_129:any;
  _text_130:any;
  _el_131:any;
  _text_132:any;
  _text_133:any;
  _el_134:any;
  _text_135:any;
  _text_136:any;
  _el_137:any;
  _el_138:any;
  _text_139:any;
  _text_140:any;
  _el_141:any;
  _text_142:any;
  _text_143:any;
  _el_144:any;
  _text_145:any;
  _el_146:any;
  _text_147:any;
  _text_148:any;
  _el_149:any;
  _text_150:any;
  _text_151:any;
  _el_152:any;
  _text_153:any;
  _text_154:any;
  _el_155:any;
  _text_156:any;
  _text_157:any;
  _text_158:any;
  _el_159:any;
  _text_160:any;
  _text_161:any;
  _el_162:any;
  _el_163:any;
  _text_164:any;
  _text_165:any;
  _el_166:any;
  _text_167:any;
  _text_168:any;
  _el_169:any;
  _text_170:any;
  _el_171:any;
  _text_172:any;
  _text_173:any;
  _el_174:any;
  _text_175:any;
  _text_176:any;
  _el_177:any;
  _text_178:any;
  _text_179:any;
  _el_180:any;
  _text_181:any;
  _text_182:any;
  _el_183:any;
  _text_184:any;
  _text_185:any;
  _text_186:any;
  _el_187:any;
  _text_188:any;
  _text_189:any;
  _el_190:any;
  _text_191:any;
  _text_192:any;
  _el_193:any;
  _text_194:any;
  _text_195:any;
  _el_196:any;
  _text_197:any;
  _text_198:any;
  _el_199:any;
  _text_200:any;
  _text_201:any;
  _el_202:any;
  _text_203:any;
  _text_204:any;
  _el_205:any;
  _el_206:any;
  _text_207:any;
  _text_208:any;
  _el_209:any;
  _text_210:any;
  _text_211:any;
  _el_212:any;
  _text_213:any;
  _text_214:any;
  _el_215:any;
  _text_216:any;
  _text_217:any;
  _el_218:any;
  _text_219:any;
  _el_220:any;
  _text_221:any;
  _text_222:any;
  _el_223:any;
  _text_224:any;
  _text_225:any;
  _el_226:any;
  _text_227:any;
  _text_228:any;
  _el_229:any;
  _text_230:any;
  _text_231:any;
  _el_232:any;
  _text_233:any;
  _text_234:any;
  _el_235:any;
  _text_236:any;
  _text_237:any;
  _text_238:any;
  _el_239:any;
  _text_240:any;
  _text_241:any;
  _el_242:any;
  _text_243:any;
  _text_244:any;
  _el_245:any;
  _text_246:any;
  _text_247:any;
  _el_248:any;
  _el_249:any;
  _text_250:any;
  _text_251:any;
  _el_252:any;
  _text_253:any;
  _text_254:any;
  _el_255:any;
  _text_256:any;
  _text_257:any;
  _el_258:any;
  _text_259:any;
  _text_260:any;
  _el_261:any;
  _text_262:any;
  _text_263:any;
  _el_264:any;
  _el_265:any;
  _text_266:any;
  _text_267:any;
  _el_268:any;
  _text_269:any;
  _text_270:any;
  _el_271:any;
  _el_272:any;
  _text_273:any;
  _text_274:any;
  _el_275:any;
  _text_276:any;
  _text_277:any;
  _el_278:any;
  _text_279:any;
  _text_280:any;
  _el_281:any;
  _text_282:any;
  _text_283:any;
  _el_284:any;
  _el_285:any;
  _text_286:any;
  _text_287:any;
  _el_288:any;
  _text_289:any;
  _text_290:any;
  _el_291:any;
  _text_292:any;
  _text_293:any;
  _el_294:any;
  _text_295:any;
  _text_296:any;
  _el_297:any;
  _text_298:any;
  _text_299:any;
  _el_300:any;
  _text_301:any;
  _text_302:any;
  _el_303:any;
  _text_304:any;
  _text_305:any;
  _el_306:any;
  _text_307:any;
  _text_308:any;
  _el_309:any;
  _text_310:any;
  _text_311:any;
  _el_312:any;
  _el_313:any;
  _text_314:any;
  _text_315:any;
  _el_316:any;
  _text_317:any;
  _text_318:any;
  _el_319:any;
  _el_320:any;
  _text_321:any;
  _text_322:any;
  _el_323:any;
  _text_324:any;
  _text_325:any;
  _el_326:any;
  _text_327:any;
  _text_328:any;
  _el_329:any;
  _el_330:any;
  _text_331:any;
  _text_332:any;
  _el_333:any;
  _text_334:any;
  _text_335:any;
  _el_336:any;
  _text_337:any;
  _text_338:any;
  _el_339:any;
  _text_340:any;
  _text_341:any;
  _el_342:any;
  _text_343:any;
  _text_344:any;
  _el_345:any;
  _el_346:any;
  _text_347:any;
  _text_348:any;
  _el_349:any;
  _text_350:any;
  _text_351:any;
  _el_352:any;
  _el_353:any;
  _text_354:any;
  _text_355:any;
  _el_356:any;
  _text_357:any;
  _text_358:any;
  _el_359:any;
  _el_360:any;
  _text_361:any;
  _text_362:any;
  _el_363:any;
  _text_364:any;
  _text_365:any;
  _el_366:any;
  _text_367:any;
  _text_368:any;
  _el_369:any;
  _el_370:any;
  _text_371:any;
  _text_372:any;
  _el_373:any;
  _text_374:any;
  _text_375:any;
  _el_376:any;
  _text_377:any;
  _text_378:any;
  _el_379:any;
  _text_380:any;
  _text_381:any;
  _el_382:any;
  _text_383:any;
  _text_384:any;
  _el_385:any;
  _text_386:any;
  _text_387:any;
  _el_388:any;
  _text_389:any;
  _el_390:any;
  _text_391:any;
  _text_392:any;
  _text_393:any;
  _text_394:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_GnuAgplLicenseComponent0,renderType_GnuAgplLicenseComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'pm-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import10.View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new import10.Wrapper_HeaderComponent();
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'legalMenu',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_4 = new import12.View_LegalMenuComponent0(this.viewUtils,this,4,this._el_4);
    this._LegalMenuComponent_4_3 = new import12.Wrapper_LegalMenuComponent();
    this.compView_4.create(this._LegalMenuComponent_4_3.context);
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','body'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Gnu affero general public license',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_6,'p',new import3.InlineArray2(2,'class','lead'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Version 3, 19 November 2007',(null as any));
    this._text_13 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'Copyright © 2007 Free Software Foundation,\n        Inc. <',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'a',new import3.InlineArray4(4,'href','http://fsf.org/','target','_blank'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'http://fsf.org/',(null as any));
    this._text_18 = this.renderer.createText(this._el_14,'>\n        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_14,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_14,'\n        Everyone is permitted to copy and distribute verbatim copies\n        of this license document, but changing it is not allowed.',(null as any));
    this._text_21 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_22,'a',new import3.InlineArray2(2,'name','preamble'),(null as any));
    this._text_24 = this.renderer.createText(this._el_22,'Preamble',(null as any));
    this._text_25 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'The GNU Affero General Public License is a free, copyleft license\n        for software and other kinds of works, specifically designed to ensure\n        cooperation with the community in the case of network server software.',(null as any));
    this._text_28 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'The licenses for most software and other practical works are\n        designed to take away your freedom to share and change the works.  By\n        contrast, our General Public Licenses are intended to guarantee your\n        freedom to share and change all versions of a program--to make sure it\n        remains free software for all its users.',(null as any));
    this._text_31 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'When we speak of free software, we are referring to freedom, not\n        price.  Our General Public Licenses are designed to make sure that you\n        have the freedom to distribute copies of free software (and charge for\n        them if you wish), that you receive source code or can get it if you\n        want it, that you can change the software or use pieces of it in new\n        free programs, and that you know you can do these things.',(null as any));
    this._text_34 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'Developers that use our General Public Licenses protect your rights\n        with two steps: (1) assert copyright on the software, and (2) offer\n        you this License which gives you legal permission to copy, distribute\n        and/or modify the software.',(null as any));
    this._text_37 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'A secondary benefit of defending all users\' freedom is that\n        improvements made in alternate versions of the program, if they\n        receive widespread use, become available for other developers to\n        incorporate.  Many developers of free software are heartened and\n        encouraged by the resulting cooperation.  However, in the case of\n        software used on network servers, this result may fail to come about.\n        The GNU General Public License permits making a modified version and\n        letting the public access it on a server without ever releasing its\n        source code to the public.',(null as any));
    this._text_40 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'The GNU Affero General Public License is designed specifically to\n        ensure that, in such cases, the modified source code becomes available\n        to the community.  It requires the operator of a network server to\n        provide the source code of the modified version running there to the\n        users of that server.  Therefore, public use of a modified version, on\n        a publicly accessible server, gives the public access to the source\n        code of the modified version.',(null as any));
    this._text_43 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'An older license, called the Affero General Public License and\n        published by Affero, was designed to accomplish similar goals.  This is\n        a different license, not a version of the Affero GPL, but Affero has\n        released a new version of the Affero GPL which permits relicensing under\n        this license.',(null as any));
    this._text_46 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'The precise terms and conditions for copying, distribution and\n        modification follow.',(null as any));
    this._text_49 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_50,'a',new import3.InlineArray2(2,'name','terms'),(null as any));
    this._text_52 = this.renderer.createText(this._el_50,'TERMS AND CONDITIONS',(null as any));
    this._text_53 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_54,'a',new import3.InlineArray2(2,'name','section0'),(null as any));
    this._text_56 = this.renderer.createText(this._el_54,'0. Definitions.',(null as any));
    this._text_57 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'"This License" refers to version 3 of the GNU Affero General Public\n        License.',(null as any));
    this._text_60 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'"Copyright" also means copyright-like laws that apply to other kinds\n        of works, such as semiconductor masks.',(null as any));
    this._text_63 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'"The Program" refers to any copyrightable work licensed under this\n        License.  Each licensee is addressed as "you".  "Licensees" and\n        "recipients" may be individuals or organizations.',(null as any));
    this._text_66 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_67 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'To "modify" a work means to copy from or adapt all or part of the work\n        in a fashion requiring copyright permission, other than the making of an\n        exact copy.  The resulting work is called a "modified version" of the\n        earlier work or a work "based on" the earlier work.',(null as any));
    this._text_69 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'A "covered work" means either the unmodified Program or a work based\n        on the Program.',(null as any));
    this._text_72 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'To "propagate" a work means to do anything with it that, without\n        permission, would make you directly or secondarily liable for\n        infringement under applicable copyright law, except executing it on a\n        computer or modifying a private copy.  Propagation includes copying,\n        distribution (with or without modification), making available to the\n        public, and in some countries other activities as well.',(null as any));
    this._text_75 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_76 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_77 = this.renderer.createText(this._el_76,'To "convey" a work means any kind of propagation that enables other\n        parties to make or receive copies.  Mere interaction with a user through\n        a computer network, with no transfer of a copy, is not conveying.',(null as any));
    this._text_78 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'An interactive user interface displays "Appropriate Legal Notices"\n        to the extent that it includes a convenient and prominently visible\n        feature that (1) displays an appropriate copyright notice, and (2)\n        tells the user that there is no warranty for the work (except to the\n        extent that warranties are provided), that licensees may convey the\n        work under this License, and how to view a copy of this License.  If\n        the interface presents a list of user commands or options, such as a\n        menu, a prominent item in the list meets this criterion.',(null as any));
    this._text_81 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_82 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_83 = import3.createRenderElement(this.renderer,this._el_82,'a',new import3.InlineArray2(2,'name','section1'),(null as any));
    this._text_84 = this.renderer.createText(this._el_82,'1. Source Code.',(null as any));
    this._text_85 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_87 = this.renderer.createText(this._el_86,'The "source code" for a work means the preferred form of the work\n        for making modifications to it.  "Object code" means any non-source\n        form of a work.',(null as any));
    this._text_88 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_89 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'A "Standard Interface" means an interface that either is an official\n        standard defined by a recognized standards body, or, in the case of\n        interfaces specified for a particular programming language, one that\n        is widely used among developers working in that language.',(null as any));
    this._text_91 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_92 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_93 = this.renderer.createText(this._el_92,'The "System Libraries" of an executable work include anything, other\n        than the work as a whole, that (a) is included in the normal form of\n        packaging a Major Component, but which is not part of that Major\n        Component, and (b) serves only to enable use of the work with that\n        Major Component, or to implement a Standard Interface for which an\n        implementation is available to the public in source code form.  A\n        "Major Component", in this context, means a major essential component\n        (kernel, window system, and so on) of the specific operating system\n        (if any) on which the executable work runs, or a compiler used to\n        produce the work, or an object code interpreter used to run it.',(null as any));
    this._text_94 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_95 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_96 = this.renderer.createText(this._el_95,'The "Corresponding Source" for a work in object code form means all\n        the source code needed to generate, install, and (for an executable\n        work) run the object code and to modify the work, including scripts to\n        control those activities.  However, it does not include the work\'s\n        System Libraries, or general-purpose tools or generally available free\n        programs which are used unmodified in performing those activities but\n        which are not part of the work.  For example, Corresponding Source\n        includes interface definition files associated with source files for\n        the work, and the source code for shared libraries and dynamically\n        linked subprograms that the work is specifically designed to require,\n        such as by intimate data communication or control flow between those\n        subprograms and other parts of the work.',(null as any));
    this._text_97 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_98 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_99 = this.renderer.createText(this._el_98,'The Corresponding Source need not include anything that users\n        can regenerate automatically from other parts of the Corresponding\n        Source.',(null as any));
    this._text_100 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_101 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_102 = this.renderer.createText(this._el_101,'The Corresponding Source for a work in source code form is that\n        same work.',(null as any));
    this._text_103 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_104 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_105 = import3.createRenderElement(this.renderer,this._el_104,'a',new import3.InlineArray2(2,'name','section2'),(null as any));
    this._text_106 = this.renderer.createText(this._el_104,'2. Basic Permissions.',(null as any));
    this._text_107 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_108 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_109 = this.renderer.createText(this._el_108,'All rights granted under this License are granted for the term of\n        copyright on the Program, and are irrevocable provided the stated\n        conditions are met.  This License explicitly affirms your unlimited\n        permission to run the unmodified Program.  The output from running a\n        covered work is covered by this License only if the output, given its\n        content, constitutes a covered work.  This License acknowledges your\n        rights of fair use or other equivalent, as provided by copyright law.',(null as any));
    this._text_110 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_111 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_112 = this.renderer.createText(this._el_111,'You may make, run and propagate covered works that you do not\n        convey, without conditions so long as your license otherwise remains\n        in force.  You may convey covered works to others for the sole purpose\n        of having them make modifications exclusively for you, or provide you\n        with facilities for running those works, provided that you comply with\n        the terms of this License in conveying all material for which you do\n        not control copyright.  Those thus making or running the covered works\n        for you must do so exclusively on your behalf, under your direction\n        and control, on terms that prohibit them from making any copies of\n        your copyrighted material outside their relationship with you.',(null as any));
    this._text_113 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_114 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_115 = this.renderer.createText(this._el_114,'Conveying under any other circumstances is permitted solely under\n        the conditions stated below.  Sublicensing is not allowed; section 10\n        makes it unnecessary.',(null as any));
    this._text_116 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_117 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_118 = import3.createRenderElement(this.renderer,this._el_117,'a',new import3.InlineArray2(2,'name','section3'),(null as any));
    this._text_119 = this.renderer.createText(this._el_117,'3. Protecting Users\' Legal Rights From Anti-Circumvention Law.',(null as any));
    this._text_120 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_121 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_122 = this.renderer.createText(this._el_121,'No covered work shall be deemed part of an effective technological\n        measure under any applicable law fulfilling obligations under article\n        11 of the WIPO copyright treaty adopted on 20 December 1996, or\n        similar laws prohibiting or restricting circumvention of such\n        measures.',(null as any));
    this._text_123 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_124 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_125 = this.renderer.createText(this._el_124,'When you convey a covered work, you waive any legal power to forbid\n        circumvention of technological measures to the extent such circumvention\n        is effected by exercising rights under this License with respect to\n        the covered work, and you disclaim any intention to limit operation or\n        modification of the work as a means of enforcing, against the work\'s\n        users, your or third parties\' legal rights to forbid circumvention of\n        technological measures.',(null as any));
    this._text_126 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_127 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_128 = import3.createRenderElement(this.renderer,this._el_127,'a',new import3.InlineArray2(2,'name','section4'),(null as any));
    this._text_129 = this.renderer.createText(this._el_127,'4. Conveying Verbatim Copies.',(null as any));
    this._text_130 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_131 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_132 = this.renderer.createText(this._el_131,'You may convey verbatim copies of the Program\'s source code as you\n        receive it, in any medium, provided that you conspicuously and\n        appropriately publish on each copy an appropriate copyright notice;\n        keep intact all notices stating that this License and any\n        non-permissive terms added in accord with section 7 apply to the code;\n        keep intact all notices of the absence of any warranty; and give all\n        recipients a copy of this License along with the Program.',(null as any));
    this._text_133 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_134 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_135 = this.renderer.createText(this._el_134,'You may charge any price or no price for each copy that you convey,\n        and you may offer support or warranty protection for a fee.',(null as any));
    this._text_136 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_137 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_138 = import3.createRenderElement(this.renderer,this._el_137,'a',new import3.InlineArray2(2,'name','section5'),(null as any));
    this._text_139 = this.renderer.createText(this._el_137,'5. Conveying Modified Source Versions.',(null as any));
    this._text_140 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_141 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_142 = this.renderer.createText(this._el_141,'You may convey a work based on the Program, or the modifications to\n        produce it from the Program, in the form of source code under the\n        terms of section 4, provided that you also meet all of these conditions:',(null as any));
    this._text_143 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_144 = import3.createRenderElement(this.renderer,this._el_6,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_145 = this.renderer.createText(this._el_144,'\n\n        ',(null as any));
    this._el_146 = import3.createRenderElement(this.renderer,this._el_144,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_147 = this.renderer.createText(this._el_146,'a) The work must carry prominent notices stating that you modified\n            it, and giving a relevant date.',(null as any));
    this._text_148 = this.renderer.createText(this._el_144,'\n\n        ',(null as any));
    this._el_149 = import3.createRenderElement(this.renderer,this._el_144,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_150 = this.renderer.createText(this._el_149,'b) The work must carry prominent notices stating that it is\n            released under this License and any conditions added under section\n            7.  This requirement modifies the requirement in section 4 to\n            "keep intact all notices".',(null as any));
    this._text_151 = this.renderer.createText(this._el_144,'\n\n        ',(null as any));
    this._el_152 = import3.createRenderElement(this.renderer,this._el_144,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_153 = this.renderer.createText(this._el_152,'c) You must license the entire work, as a whole, under this\n            License to anyone who comes into possession of a copy.  This\n            License will therefore apply, along with any applicable section 7\n            additional terms, to the whole of the work, and all its parts,\n            regardless of how they are packaged.  This License gives no\n            permission to license the work in any other way, but it does not\n            invalidate such permission if you have separately received it.',(null as any));
    this._text_154 = this.renderer.createText(this._el_144,'\n\n        ',(null as any));
    this._el_155 = import3.createRenderElement(this.renderer,this._el_144,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_156 = this.renderer.createText(this._el_155,'d) If the work has interactive user interfaces, each must display\n            Appropriate Legal Notices; however, if the Program has interactive\n            interfaces that do not display Appropriate Legal Notices, your\n            work need not make them do so.',(null as any));
    this._text_157 = this.renderer.createText(this._el_144,'\n\n        ',(null as any));
    this._text_158 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_159 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_160 = this.renderer.createText(this._el_159,'A compilation of a covered work with other separate and independent\n        works, which are not by their nature extensions of the covered work,\n        and which are not combined with it such as to form a larger program,\n        in or on a volume of a storage or distribution medium, is called an\n        "aggregate" if the compilation and its resulting copyright are not\n        used to limit the access or legal rights of the compilation\'s users\n        beyond what the individual works permit.  Inclusion of a covered work\n        in an aggregate does not cause this License to apply to the other\n        parts of the aggregate.',(null as any));
    this._text_161 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_162 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_163 = import3.createRenderElement(this.renderer,this._el_162,'a',new import3.InlineArray2(2,'name','section6'),(null as any));
    this._text_164 = this.renderer.createText(this._el_162,'6. Conveying Non-Source Forms.',(null as any));
    this._text_165 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_166 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_167 = this.renderer.createText(this._el_166,'You may convey a covered work in object code form under the terms\n        of sections 4 and 5, provided that you also convey the\n        machine-readable Corresponding Source under the terms of this License,\n        in one of these ways:',(null as any));
    this._text_168 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_169 = import3.createRenderElement(this.renderer,this._el_6,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_170 = this.renderer.createText(this._el_169,'\n\n        ',(null as any));
    this._el_171 = import3.createRenderElement(this.renderer,this._el_169,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_172 = this.renderer.createText(this._el_171,'a) Convey the object code in, or embodied in, a physical product\n            (including a physical distribution medium), accompanied by the\n            Corresponding Source fixed on a durable physical medium\n            customarily used for software interchange.',(null as any));
    this._text_173 = this.renderer.createText(this._el_169,'\n\n        ',(null as any));
    this._el_174 = import3.createRenderElement(this.renderer,this._el_169,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_175 = this.renderer.createText(this._el_174,'b) Convey the object code in, or embodied in, a physical product\n            (including a physical distribution medium), accompanied by a\n            written offer, valid for at least three years and valid for as\n            long as you offer spare parts or customer support for that product\n            model, to give anyone who possesses the object code either (1) a\n            copy of the Corresponding Source for all the software in the\n            product that is covered by this License, on a durable physical\n            medium customarily used for software interchange, for a price no\n            more than your reasonable cost of physically performing this\n            conveying of source, or (2) access to copy the\n            Corresponding Source from a network server at no charge.',(null as any));
    this._text_176 = this.renderer.createText(this._el_169,'\n\n        ',(null as any));
    this._el_177 = import3.createRenderElement(this.renderer,this._el_169,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_178 = this.renderer.createText(this._el_177,'c) Convey individual copies of the object code with a copy of the\n            written offer to provide the Corresponding Source.  This\n            alternative is allowed only occasionally and noncommercially, and\n            only if you received the object code with such an offer, in accord\n            with subsection 6b.',(null as any));
    this._text_179 = this.renderer.createText(this._el_169,'\n\n        ',(null as any));
    this._el_180 = import3.createRenderElement(this.renderer,this._el_169,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_181 = this.renderer.createText(this._el_180,'d) Convey the object code by offering access from a designated\n            place (gratis or for a charge), and offer equivalent access to the\n            Corresponding Source in the same way through the same place at no\n            further charge.  You need not require recipients to copy the\n            Corresponding Source along with the object code.  If the place to\n            copy the object code is a network server, the Corresponding Source\n            may be on a different server (operated by you or a third party)\n            that supports equivalent copying facilities, provided you maintain\n            clear directions next to the object code saying where to find the\n            Corresponding Source.  Regardless of what server hosts the\n            Corresponding Source, you remain obligated to ensure that it is\n            available for as long as needed to satisfy these requirements.',(null as any));
    this._text_182 = this.renderer.createText(this._el_169,'\n\n        ',(null as any));
    this._el_183 = import3.createRenderElement(this.renderer,this._el_169,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_184 = this.renderer.createText(this._el_183,'e) Convey the object code using peer-to-peer transmission, provided\n            you inform other peers where the object code and Corresponding\n            Source of the work are being offered to the general public at no\n            charge under subsection 6d.',(null as any));
    this._text_185 = this.renderer.createText(this._el_169,'\n\n        ',(null as any));
    this._text_186 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_187 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_188 = this.renderer.createText(this._el_187,'A separable portion of the object code, whose source code is excluded\n        from the Corresponding Source as a System Library, need not be\n        included in conveying the object code work.',(null as any));
    this._text_189 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_190 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_191 = this.renderer.createText(this._el_190,'A "User Product" is either (1) a "consumer product", which means any\n        tangible personal property which is normally used for personal, family,\n        or household purposes, or (2) anything designed or sold for incorporation\n        into a dwelling.  In determining whether a product is a consumer product,\n        doubtful cases shall be resolved in favor of coverage.  For a particular\n        product received by a particular user, "normally used" refers to a\n        typical or common use of that class of product, regardless of the status\n        of the particular user or of the way in which the particular user\n        actually uses, or expects or is expected to use, the product.  A product\n        is a consumer product regardless of whether the product has substantial\n        commercial, industrial or non-consumer uses, unless such uses represent\n        the only significant mode of use of the product.',(null as any));
    this._text_192 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_193 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_194 = this.renderer.createText(this._el_193,'"Installation Information" for a User Product means any methods,\n        procedures, authorization keys, or other information required to install\n        and execute modified versions of a covered work in that User Product from\n        a modified version of its Corresponding Source.  The information must\n        suffice to ensure that the continued functioning of the modified object\n        code is in no case prevented or interfered with solely because\n        modification has been made.',(null as any));
    this._text_195 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_196 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_197 = this.renderer.createText(this._el_196,'If you convey an object code work under this section in, or with, or\n        specifically for use in, a User Product, and the conveying occurs as\n        part of a transaction in which the right of possession and use of the\n        User Product is transferred to the recipient in perpetuity or for a\n        fixed term (regardless of how the transaction is characterized), the\n        Corresponding Source conveyed under this section must be accompanied\n        by the Installation Information.  But this requirement does not apply\n        if neither you nor any third party retains the ability to install\n        modified object code on the User Product (for example, the work has\n        been installed in ROM).',(null as any));
    this._text_198 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_199 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_200 = this.renderer.createText(this._el_199,'The requirement to provide Installation Information does not include a\n        requirement to continue to provide support service, warranty, or updates\n        for a work that has been modified or installed by the recipient, or for\n        the User Product in which it has been modified or installed.  Access to a\n        network may be denied when the modification itself materially and\n        adversely affects the operation of the network or violates the rules and\n        protocols for communication across the network.',(null as any));
    this._text_201 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_202 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_203 = this.renderer.createText(this._el_202,'Corresponding Source conveyed, and Installation Information provided,\n        in accord with this section must be in a format that is publicly\n        documented (and with an implementation available to the public in\n        source code form), and must require no special password or key for\n        unpacking, reading or copying.',(null as any));
    this._text_204 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_205 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_206 = import3.createRenderElement(this.renderer,this._el_205,'a',new import3.InlineArray2(2,'name','section7'),(null as any));
    this._text_207 = this.renderer.createText(this._el_205,'7. Additional Terms.',(null as any));
    this._text_208 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_209 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_210 = this.renderer.createText(this._el_209,'"Additional permissions" are terms that supplement the terms of this\n        License by making exceptions from one or more of its conditions.\n        Additional permissions that are applicable to the entire Program shall\n        be treated as though they were included in this License, to the extent\n        that they are valid under applicable law.  If additional permissions\n        apply only to part of the Program, that part may be used separately\n        under those permissions, but the entire Program remains governed by\n        this License without regard to the additional permissions.',(null as any));
    this._text_211 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_212 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_213 = this.renderer.createText(this._el_212,'When you convey a copy of a covered work, you may at your option\n        remove any additional permissions from that copy, or from any part of\n        it.  (Additional permissions may be written to require their own\n        removal in certain cases when you modify the work.)  You may place\n        additional permissions on material, added by you to a covered work,\n        for which you have or can give appropriate copyright permission.',(null as any));
    this._text_214 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_215 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_216 = this.renderer.createText(this._el_215,'Notwithstanding any other provision of this License, for material you\n        add to a covered work, you may (if authorized by the copyright holders of\n        that material) supplement the terms of this License with terms:',(null as any));
    this._text_217 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_218 = import3.createRenderElement(this.renderer,this._el_6,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_219 = this.renderer.createText(this._el_218,'\n\n        ',(null as any));
    this._el_220 = import3.createRenderElement(this.renderer,this._el_218,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_221 = this.renderer.createText(this._el_220,'a) Disclaiming warranty or limiting liability differently from the\n            terms of sections 15 and 16 of this License; or',(null as any));
    this._text_222 = this.renderer.createText(this._el_218,'\n\n        ',(null as any));
    this._el_223 = import3.createRenderElement(this.renderer,this._el_218,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_224 = this.renderer.createText(this._el_223,'b) Requiring preservation of specified reasonable legal notices or\n            author attributions in that material or in the Appropriate Legal\n            Notices displayed by works containing it; or',(null as any));
    this._text_225 = this.renderer.createText(this._el_218,'\n\n        ',(null as any));
    this._el_226 = import3.createRenderElement(this.renderer,this._el_218,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_227 = this.renderer.createText(this._el_226,'c) Prohibiting misrepresentation of the origin of that material, or\n            requiring that modified versions of such material be marked in\n            reasonable ways as different from the original version; or',(null as any));
    this._text_228 = this.renderer.createText(this._el_218,'\n\n        ',(null as any));
    this._el_229 = import3.createRenderElement(this.renderer,this._el_218,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_230 = this.renderer.createText(this._el_229,'d) Limiting the use for publicity purposes of names of licensors or\n            authors of the material; or',(null as any));
    this._text_231 = this.renderer.createText(this._el_218,'\n\n        ',(null as any));
    this._el_232 = import3.createRenderElement(this.renderer,this._el_218,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_233 = this.renderer.createText(this._el_232,'e) Declining to grant rights under trademark law for use of some\n            trade names, trademarks, or service marks; or',(null as any));
    this._text_234 = this.renderer.createText(this._el_218,'\n\n        ',(null as any));
    this._el_235 = import3.createRenderElement(this.renderer,this._el_218,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_236 = this.renderer.createText(this._el_235,'f) Requiring indemnification of licensors and authors of that\n            material by anyone who conveys the material (or modified versions of\n            it) with contractual assumptions of liability to the recipient, for\n            any liability that these contractual assumptions directly impose on\n            those licensors and authors.',(null as any));
    this._text_237 = this.renderer.createText(this._el_218,'\n\n        ',(null as any));
    this._text_238 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_239 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_240 = this.renderer.createText(this._el_239,'All other non-permissive additional terms are considered "further\n        restrictions" within the meaning of section 10.  If the Program as you\n        received it, or any part of it, contains a notice stating that it is\n        governed by this License along with a term that is a further restriction,\n        you may remove that term.  If a license document contains a further\n        restriction but permits relicensing or conveying under this License, you\n        may add to a covered work material governed by the terms of that license\n        document, provided that the further restriction does not survive such\n        relicensing or conveying.',(null as any));
    this._text_241 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_242 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_243 = this.renderer.createText(this._el_242,'If you add terms to a covered work in accord with this section, you\n        must place, in the relevant source files, a statement of the\n        additional terms that apply to those files, or a notice indicating\n        where to find the applicable terms.',(null as any));
    this._text_244 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_245 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_246 = this.renderer.createText(this._el_245,'Additional terms, permissive or non-permissive, may be stated in the\n        form of a separately written license, or stated as exceptions;\n        the above requirements apply either way.',(null as any));
    this._text_247 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_248 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_249 = import3.createRenderElement(this.renderer,this._el_248,'a',new import3.InlineArray2(2,'name','section8'),(null as any));
    this._text_250 = this.renderer.createText(this._el_248,'8. Termination.',(null as any));
    this._text_251 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_252 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_253 = this.renderer.createText(this._el_252,'You may not propagate or modify a covered work except as expressly\n        provided under this License.  Any attempt otherwise to propagate or\n        modify it is void, and will automatically terminate your rights under\n        this License (including any patent licenses granted under the third\n        paragraph of section 11).',(null as any));
    this._text_254 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_255 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_256 = this.renderer.createText(this._el_255,'However, if you cease all violation of this License, then your\n        license from a particular copyright holder is reinstated (a)\n        provisionally, unless and until the copyright holder explicitly and\n        finally terminates your license, and (b) permanently, if the copyright\n        holder fails to notify you of the violation by some reasonable means\n        prior to 60 days after the cessation.',(null as any));
    this._text_257 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_258 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_259 = this.renderer.createText(this._el_258,'Moreover, your license from a particular copyright holder is\n        reinstated permanently if the copyright holder notifies you of the\n        violation by some reasonable means, this is the first time you have\n        received notice of violation of this License (for any work) from that\n        copyright holder, and you cure the violation prior to 30 days after\n        your receipt of the notice.',(null as any));
    this._text_260 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_261 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_262 = this.renderer.createText(this._el_261,'Termination of your rights under this section does not terminate the\n        licenses of parties who have received copies or rights from you under\n        this License.  If your rights have been terminated and not permanently\n        reinstated, you do not qualify to receive new licenses for the same\n        material under section 10.',(null as any));
    this._text_263 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_264 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_265 = import3.createRenderElement(this.renderer,this._el_264,'a',new import3.InlineArray2(2,'name','section9'),(null as any));
    this._text_266 = this.renderer.createText(this._el_264,'9. Acceptance Not Required for Having Copies.',(null as any));
    this._text_267 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_268 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_269 = this.renderer.createText(this._el_268,'You are not required to accept this License in order to receive or\n        run a copy of the Program.  Ancillary propagation of a covered work\n        occurring solely as a consequence of using peer-to-peer transmission\n        to receive a copy likewise does not require acceptance.  However,\n        nothing other than this License grants you permission to propagate or\n        modify any covered work.  These actions infringe copyright if you do\n        not accept this License.  Therefore, by modifying or propagating a\n        covered work, you indicate your acceptance of this License to do so.',(null as any));
    this._text_270 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_271 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_272 = import3.createRenderElement(this.renderer,this._el_271,'a',new import3.InlineArray2(2,'name','section10'),(null as any));
    this._text_273 = this.renderer.createText(this._el_271,'10. Automatic Licensing of Downstream Recipients.',(null as any));
    this._text_274 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_275 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_276 = this.renderer.createText(this._el_275,'Each time you convey a covered work, the recipient automatically\n        receives a license from the original licensors, to run, modify and\n        propagate that work, subject to this License.  You are not responsible\n        for enforcing compliance by third parties with this License.',(null as any));
    this._text_277 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_278 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_279 = this.renderer.createText(this._el_278,'An "entity transaction" is a transaction transferring control of an\n        organization, or substantially all assets of one, or subdividing an\n        organization, or merging organizations.  If propagation of a covered\n        work results from an entity transaction, each party to that\n        transaction who receives a copy of the work also receives whatever\n        licenses to the work the party\'s predecessor in interest had or could\n        give under the previous paragraph, plus a right to possession of the\n        Corresponding Source of the work from the predecessor in interest, if\n        the predecessor has it or can get it with reasonable efforts.',(null as any));
    this._text_280 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_281 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_282 = this.renderer.createText(this._el_281,'You may not impose any further restrictions on the exercise of the\n        rights granted or affirmed under this License.  For example, you may\n        not impose a license fee, royalty, or other charge for exercise of\n        rights granted under this License, and you may not initiate litigation\n        (including a cross-claim or counterclaim in a lawsuit) alleging that\n        any patent claim is infringed by making, using, selling, offering for\n        sale, or importing the Program or any portion of it.',(null as any));
    this._text_283 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_284 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_285 = import3.createRenderElement(this.renderer,this._el_284,'a',new import3.InlineArray2(2,'name','section11'),(null as any));
    this._text_286 = this.renderer.createText(this._el_284,'11. Patents.',(null as any));
    this._text_287 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_288 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_289 = this.renderer.createText(this._el_288,'A "contributor" is a copyright holder who authorizes use under this\n        License of the Program or a work on which the Program is based.  The\n        work thus licensed is called the contributor\'s "contributor version".',(null as any));
    this._text_290 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_291 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_292 = this.renderer.createText(this._el_291,'A contributor\'s "essential patent claims" are all patent claims\n        owned or controlled by the contributor, whether already acquired or\n        hereafter acquired, that would be infringed by some manner, permitted\n        by this License, of making, using, or selling its contributor version,\n        but do not include claims that would be infringed only as a\n        consequence of further modification of the contributor version.  For\n        purposes of this definition, "control" includes the right to grant\n        patent sublicenses in a manner consistent with the requirements of\n        this License.',(null as any));
    this._text_293 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_294 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_295 = this.renderer.createText(this._el_294,'Each contributor grants you a non-exclusive, worldwide, royalty-free\n        patent license under the contributor\'s essential patent claims, to\n        make, use, sell, offer for sale, import and otherwise run, modify and\n        propagate the contents of its contributor version.',(null as any));
    this._text_296 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_297 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_298 = this.renderer.createText(this._el_297,'In the following three paragraphs, a "patent license" is any express\n        agreement or commitment, however denominated, not to enforce a patent\n        (such as an express permission to practice a patent or covenant not to\n        sue for patent infringement).  To "grant" such a patent license to a\n        party means to make such an agreement or commitment not to enforce a\n        patent against the party.',(null as any));
    this._text_299 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_300 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_301 = this.renderer.createText(this._el_300,'If you convey a covered work, knowingly relying on a patent license,\n        and the Corresponding Source of the work is not available for anyone\n        to copy, free of charge and under the terms of this License, through a\n        publicly available network server or other readily accessible means,\n        then you must either (1) cause the Corresponding Source to be so\n        available, or (2) arrange to deprive yourself of the benefit of the\n        patent license for this particular work, or (3) arrange, in a manner\n        consistent with the requirements of this License, to extend the patent\n        license to downstream recipients.  "Knowingly relying" means you have\n        actual knowledge that, but for the patent license, your conveying the\n        covered work in a country, or your recipient\'s use of the covered work\n        in a country, would infringe one or more identifiable patents in that\n        country that you have reason to believe are valid.',(null as any));
    this._text_302 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_303 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_304 = this.renderer.createText(this._el_303,'If, pursuant to or in connection with a single transaction or\n        arrangement, you convey, or propagate by procuring conveyance of, a\n        covered work, and grant a patent license to some of the parties\n        receiving the covered work authorizing them to use, propagate, modify\n        or convey a specific copy of the covered work, then the patent license\n        you grant is automatically extended to all recipients of the covered\n        work and works based on it.',(null as any));
    this._text_305 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_306 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_307 = this.renderer.createText(this._el_306,'A patent license is "discriminatory" if it does not include within\n        the scope of its coverage, prohibits the exercise of, or is\n        conditioned on the non-exercise of one or more of the rights that are\n        specifically granted under this License.  You may not convey a covered\n        work if you are a party to an arrangement with a third party that is\n        in the business of distributing software, under which you make payment\n        to the third party based on the extent of your activity of conveying\n        the work, and under which the third party grants, to any of the\n        parties who would receive the covered work from you, a discriminatory\n        patent license (a) in connection with copies of the covered work\n        conveyed by you (or copies made from those copies), or (b) primarily\n        for and in connection with specific products or compilations that\n        contain the covered work, unless you entered into that arrangement,\n        or that patent license was granted, prior to 28 March 2007.',(null as any));
    this._text_308 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_309 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_310 = this.renderer.createText(this._el_309,'Nothing in this License shall be construed as excluding or limiting\n        any implied license or other defenses to infringement that may\n        otherwise be available to you under applicable patent law.',(null as any));
    this._text_311 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_312 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_313 = import3.createRenderElement(this.renderer,this._el_312,'a',new import3.InlineArray2(2,'name','section12'),(null as any));
    this._text_314 = this.renderer.createText(this._el_312,'12. No Surrender of Others\' Freedom.',(null as any));
    this._text_315 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_316 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_317 = this.renderer.createText(this._el_316,'If conditions are imposed on you (whether by court order, agreement or\n        otherwise) that contradict the conditions of this License, they do not\n        excuse you from the conditions of this License.  If you cannot convey a\n        covered work so as to satisfy simultaneously your obligations under this\n        License and any other pertinent obligations, then as a consequence you may\n        not convey it at all.  For example, if you agree to terms that obligate you\n        to collect a royalty for further conveying from those to whom you convey\n        the Program, the only way you could satisfy both those terms and this\n        License would be to refrain entirely from conveying the Program.',(null as any));
    this._text_318 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_319 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_320 = import3.createRenderElement(this.renderer,this._el_319,'a',new import3.InlineArray2(2,'name','section13'),(null as any));
    this._text_321 = this.renderer.createText(this._el_319,'13. Remote Network Interaction; Use with the GNU General Public License.',(null as any));
    this._text_322 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_323 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_324 = this.renderer.createText(this._el_323,'Notwithstanding any other provision of this License, if you modify the\n        Program, your modified version must prominently offer all users\n        interacting with it remotely through a computer network (if your version\n        supports such interaction) an opportunity to receive the Corresponding\n        Source of your version by providing access to the Corresponding Source\n        from a network server at no charge, through some standard or customary\n        means of facilitating copying of software.  This Corresponding Source\n        shall include the Corresponding Source for any work covered by version 3\n        of the GNU General Public License that is incorporated pursuant to the\n        following paragraph.',(null as any));
    this._text_325 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_326 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_327 = this.renderer.createText(this._el_326,'Notwithstanding any other provision of this License, you have permission\n        to link or combine any covered work with a work licensed under version 3\n        of the GNU General Public License into a single combined work, and to\n        convey the resulting work.  The terms of this License will continue to\n        apply to the part which is the covered work, but the work with which it is\n        combined will remain governed by version 3 of the GNU General Public\n        License.',(null as any));
    this._text_328 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_329 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_330 = import3.createRenderElement(this.renderer,this._el_329,'a',new import3.InlineArray2(2,'name','section14'),(null as any));
    this._text_331 = this.renderer.createText(this._el_329,'14. Revised Versions of this License.',(null as any));
    this._text_332 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_333 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_334 = this.renderer.createText(this._el_333,'The Free Software Foundation may publish revised and/or new versions of\n        the GNU Affero General Public License from time to time.  Such new\n        versions will be similar in spirit to the present version, but may differ\n        in detail to address new problems or concerns.',(null as any));
    this._text_335 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_336 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_337 = this.renderer.createText(this._el_336,'Each version is given a distinguishing version number.  If the\n        Program specifies that a certain numbered version of the GNU Affero\n        General Public License "or any later version" applies to it, you have\n        the option of following the terms and conditions either of that\n        numbered version or of any later version published by the Free\n        Software Foundation.  If the Program does not specify a version number\n        of the GNU Affero General Public License, you may choose any version\n        ever published by the Free Software Foundation.',(null as any));
    this._text_338 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_339 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_340 = this.renderer.createText(this._el_339,'If the Program specifies that a proxy can decide which future\n        versions of the GNU Affero General Public License can be used, that\n        proxy\'s public statement of acceptance of a version permanently\n        authorizes you to choose that version for the Program.',(null as any));
    this._text_341 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_342 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_343 = this.renderer.createText(this._el_342,'Later license versions may give you additional or different\n        permissions.  However, no additional obligations are imposed on any\n        author or copyright holder as a result of your choosing to follow a\n        later version.',(null as any));
    this._text_344 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_345 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_346 = import3.createRenderElement(this.renderer,this._el_345,'a',new import3.InlineArray2(2,'name','section15'),(null as any));
    this._text_347 = this.renderer.createText(this._el_345,'15. Disclaimer of Warranty.',(null as any));
    this._text_348 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_349 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_350 = this.renderer.createText(this._el_349,'THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY\n        APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT\n        HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY\n        OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,\n        THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n        PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM\n        IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF\n        ALL NECESSARY SERVICING, REPAIR OR CORRECTION.',(null as any));
    this._text_351 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_352 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_353 = import3.createRenderElement(this.renderer,this._el_352,'a',new import3.InlineArray2(2,'name','section16'),(null as any));
    this._text_354 = this.renderer.createText(this._el_352,'16. Limitation of Liability.',(null as any));
    this._text_355 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_356 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_357 = this.renderer.createText(this._el_356,'IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING\n        WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS\n        THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY\n        GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE\n        USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF\n        DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD\n        PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS),\n        EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF\n        SUCH DAMAGES.',(null as any));
    this._text_358 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_359 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_360 = import3.createRenderElement(this.renderer,this._el_359,'a',new import3.InlineArray2(2,'name','section17'),(null as any));
    this._text_361 = this.renderer.createText(this._el_359,'17. Interpretation of Sections 15 and 16.',(null as any));
    this._text_362 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_363 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_364 = this.renderer.createText(this._el_363,'If the disclaimer of warranty and limitation of liability provided\n        above cannot be given local legal effect according to their terms,\n        reviewing courts shall apply local law that most closely approximates\n        an absolute waiver of all civil liability in connection with the\n        Program, unless a warranty or assumption of liability accompanies a\n        copy of the Program in return for a fee.',(null as any));
    this._text_365 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_366 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_367 = this.renderer.createText(this._el_366,'END OF TERMS AND CONDITIONS',(null as any));
    this._text_368 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_369 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_370 = import3.createRenderElement(this.renderer,this._el_369,'a',new import3.InlineArray2(2,'name','howto'),(null as any));
    this._text_371 = this.renderer.createText(this._el_369,'How to Apply These Terms to Your New Programs',(null as any));
    this._text_372 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_373 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_374 = this.renderer.createText(this._el_373,'If you develop a new program, and you want it to be of the greatest\n        possible use to the public, the best way to achieve this is to make it\n        free software which everyone can redistribute and change under these terms.',(null as any));
    this._text_375 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_376 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_377 = this.renderer.createText(this._el_376,'To do so, attach the following notices to the program.  It is safest\n        to attach them to the start of each source file to most effectively\n        state the exclusion of warranty; and each file should have at least\n        the "copyright" line and a pointer to where the full notice is found.',(null as any));
    this._text_378 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_379 = import3.createRenderElement(this.renderer,this._el_6,'pre',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_380 = this.renderer.createText(this._el_379,'<one line to give the program\'s name and a brief idea of what it does.>\n    Copyright (C) <year>  <name of author>\n\n    This program is free software: you can redistribute it and/or modify\n    it under the terms of the GNU Affero General Public License as\n    published by the Free Software Foundation, either version 3 of the\n    License, or (at your option) any later version.\n\n    This program is distributed in the hope that it will be useful,\n    but WITHOUT ANY WARRANTY; without even the implied warranty of\n    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n    GNU Affero General Public License for more details.\n\n    You should have received a copy of the GNU Affero General Public License\n    along with this program.  If not, see <http://www.gnu.org/licenses/>.\n        ',(null as any));
    this._text_381 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_382 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_383 = this.renderer.createText(this._el_382,'Also add information on how to contact you by electronic and paper mail.',(null as any));
    this._text_384 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_385 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_386 = this.renderer.createText(this._el_385,'If your software can interact with users remotely through a computer\n        network, you should also make sure that it provides a way for users to\n        get its source.  For example, if your program is a web application, its\n        interface could display a "Source" link that leads users to an archive\n        of the code.  There are many ways you could offer source, and different\n        solutions will be better for different programs; see section 13 for the\n        specific requirements.',(null as any));
    this._text_387 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_388 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_389 = this.renderer.createText(this._el_388,'You should also get your employer (if you work as a programmer) or school,\n        if any, to sign a "copyright disclaimer" for the program, if necessary.\n        For more information on this, and how to apply and follow the GNU AGPL, see\n        <',(null as any));
    this._el_390 = import3.createRenderElement(this.renderer,this._el_388,'a',new import3.InlineArray4(4,'href','http://www.gnu.org/licenses/','target','_blank'),(null as any));
    this._text_391 = this.renderer.createText(this._el_390,'http://www.gnu.org/licenses/',(null as any));
    this._text_392 = this.renderer.createText(this._el_388,'>.',(null as any));
    this._text_393 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_394 = this.renderer.createText(this._el_2,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._el_83,
      this._text_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._text_100,
      this._el_101,
      this._text_102,
      this._text_103,
      this._el_104,
      this._el_105,
      this._text_106,
      this._text_107,
      this._el_108,
      this._text_109,
      this._text_110,
      this._el_111,
      this._text_112,
      this._text_113,
      this._el_114,
      this._text_115,
      this._text_116,
      this._el_117,
      this._el_118,
      this._text_119,
      this._text_120,
      this._el_121,
      this._text_122,
      this._text_123,
      this._el_124,
      this._text_125,
      this._text_126,
      this._el_127,
      this._el_128,
      this._text_129,
      this._text_130,
      this._el_131,
      this._text_132,
      this._text_133,
      this._el_134,
      this._text_135,
      this._text_136,
      this._el_137,
      this._el_138,
      this._text_139,
      this._text_140,
      this._el_141,
      this._text_142,
      this._text_143,
      this._el_144,
      this._text_145,
      this._el_146,
      this._text_147,
      this._text_148,
      this._el_149,
      this._text_150,
      this._text_151,
      this._el_152,
      this._text_153,
      this._text_154,
      this._el_155,
      this._text_156,
      this._text_157,
      this._text_158,
      this._el_159,
      this._text_160,
      this._text_161,
      this._el_162,
      this._el_163,
      this._text_164,
      this._text_165,
      this._el_166,
      this._text_167,
      this._text_168,
      this._el_169,
      this._text_170,
      this._el_171,
      this._text_172,
      this._text_173,
      this._el_174,
      this._text_175,
      this._text_176,
      this._el_177,
      this._text_178,
      this._text_179,
      this._el_180,
      this._text_181,
      this._text_182,
      this._el_183,
      this._text_184,
      this._text_185,
      this._text_186,
      this._el_187,
      this._text_188,
      this._text_189,
      this._el_190,
      this._text_191,
      this._text_192,
      this._el_193,
      this._text_194,
      this._text_195,
      this._el_196,
      this._text_197,
      this._text_198,
      this._el_199,
      this._text_200,
      this._text_201,
      this._el_202,
      this._text_203,
      this._text_204,
      this._el_205,
      this._el_206,
      this._text_207,
      this._text_208,
      this._el_209,
      this._text_210,
      this._text_211,
      this._el_212,
      this._text_213,
      this._text_214,
      this._el_215,
      this._text_216,
      this._text_217,
      this._el_218,
      this._text_219,
      this._el_220,
      this._text_221,
      this._text_222,
      this._el_223,
      this._text_224,
      this._text_225,
      this._el_226,
      this._text_227,
      this._text_228,
      this._el_229,
      this._text_230,
      this._text_231,
      this._el_232,
      this._text_233,
      this._text_234,
      this._el_235,
      this._text_236,
      this._text_237,
      this._text_238,
      this._el_239,
      this._text_240,
      this._text_241,
      this._el_242,
      this._text_243,
      this._text_244,
      this._el_245,
      this._text_246,
      this._text_247,
      this._el_248,
      this._el_249,
      this._text_250,
      this._text_251,
      this._el_252,
      this._text_253,
      this._text_254,
      this._el_255,
      this._text_256,
      this._text_257,
      this._el_258,
      this._text_259,
      this._text_260,
      this._el_261,
      this._text_262,
      this._text_263,
      this._el_264,
      this._el_265,
      this._text_266,
      this._text_267,
      this._el_268,
      this._text_269,
      this._text_270,
      this._el_271,
      this._el_272,
      this._text_273,
      this._text_274,
      this._el_275,
      this._text_276,
      this._text_277,
      this._el_278,
      this._text_279,
      this._text_280,
      this._el_281,
      this._text_282,
      this._text_283,
      this._el_284,
      this._el_285,
      this._text_286,
      this._text_287,
      this._el_288,
      this._text_289,
      this._text_290,
      this._el_291,
      this._text_292,
      this._text_293,
      this._el_294,
      this._text_295,
      this._text_296,
      this._el_297,
      this._text_298,
      this._text_299,
      this._el_300,
      this._text_301,
      this._text_302,
      this._el_303,
      this._text_304,
      this._text_305,
      this._el_306,
      this._text_307,
      this._text_308,
      this._el_309,
      this._text_310,
      this._text_311,
      this._el_312,
      this._el_313,
      this._text_314,
      this._text_315,
      this._el_316,
      this._text_317,
      this._text_318,
      this._el_319,
      this._el_320,
      this._text_321,
      this._text_322,
      this._el_323,
      this._text_324,
      this._text_325,
      this._el_326,
      this._text_327,
      this._text_328,
      this._el_329,
      this._el_330,
      this._text_331,
      this._text_332,
      this._el_333,
      this._text_334,
      this._text_335,
      this._el_336,
      this._text_337,
      this._text_338,
      this._el_339,
      this._text_340,
      this._text_341,
      this._el_342,
      this._text_343,
      this._text_344,
      this._el_345,
      this._el_346,
      this._text_347,
      this._text_348,
      this._el_349,
      this._text_350,
      this._text_351,
      this._el_352,
      this._el_353,
      this._text_354,
      this._text_355,
      this._el_356,
      this._text_357,
      this._text_358,
      this._el_359,
      this._el_360,
      this._text_361,
      this._text_362,
      this._el_363,
      this._text_364,
      this._text_365,
      this._el_366,
      this._text_367,
      this._text_368,
      this._el_369,
      this._el_370,
      this._text_371,
      this._text_372,
      this._el_373,
      this._text_374,
      this._text_375,
      this._el_376,
      this._text_377,
      this._text_378,
      this._el_379,
      this._text_380,
      this._text_381,
      this._el_382,
      this._text_383,
      this._text_384,
      this._el_385,
      this._text_386,
      this._text_387,
      this._el_388,
      this._text_389,
      this._el_390,
      this._text_391,
      this._text_392,
      this._text_393,
      this._text_394
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    if (((token === import11.LegalMenuComponent) && (4 === requestNodeIndex))) { return this._LegalMenuComponent_4_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._LegalMenuComponent_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
    this.compView_4.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this.compView_4.destroy();
  }
}