/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.menu[_ngcontent-%COMP%]{position:relative;min-height:1px;padding-left:15px;padding-right:15px}@media (min-width: 992px){.menu[_ngcontent-%COMP%]{float:left;width:25%}}.menu[_ngcontent-%COMP%]   .list-group[_ngcontent-%COMP%]{margin-top:30px}.body[_ngcontent-%COMP%]{position:relative;min-height:1px;padding-left:15px;padding-right:15px}@media (min-width: 992px){.body[_ngcontent-%COMP%]{float:left;width:75%}}.body[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%]:first-of-type{margin-top:30px}'];