/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './privacy-policy.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './legal.component.css.shim';
import * as import9 from '../common/header/header.component';
import * as import10 from '../common/header/header.component.ngfactory';
import * as import11 from './legal-menu.component';
import * as import12 from './legal-menu.component.ngfactory';
export class Wrapper_PrivacyPolicyComponent {
  /*private*/ _eventHandler:Function;
  context:import0.PrivacyPolicyComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.PrivacyPolicyComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_PrivacyPolicyComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_PrivacyPolicyComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.PrivacyPolicyComponent>;
  _PrivacyPolicyComponent_0_3:Wrapper_PrivacyPolicyComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PrivacyPolicyComponent_Host0,renderType_PrivacyPolicyComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_PrivacyPolicyComponent0(this.viewUtils,this,0,this._el_0);
    this._PrivacyPolicyComponent_0_3 = new Wrapper_PrivacyPolicyComponent();
    this.compView_0.create(this._PrivacyPolicyComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._PrivacyPolicyComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PrivacyPolicyComponent) && (0 === requestNodeIndex))) { return this._PrivacyPolicyComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PrivacyPolicyComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const PrivacyPolicyComponentNgFactory:import7.ComponentFactory<import0.PrivacyPolicyComponent> = new import7.ComponentFactory<import0.PrivacyPolicyComponent>('ng-component',View_PrivacyPolicyComponent_Host0,import0.PrivacyPolicyComponent);
const styles_PrivacyPolicyComponent:any[] = [import8.styles];
var renderType_PrivacyPolicyComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_PrivacyPolicyComponent,{});
export class View_PrivacyPolicyComponent0 extends import1.AppView<import0.PrivacyPolicyComponent> {
  _el_0:any;
  compView_0:import1.AppView<import9.HeaderComponent>;
  _HeaderComponent_0_3:import10.Wrapper_HeaderComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import11.LegalMenuComponent>;
  _LegalMenuComponent_4_3:import12.Wrapper_LegalMenuComponent;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _text_87:any;
  _el_88:any;
  _text_89:any;
  _text_90:any;
  _el_91:any;
  _text_92:any;
  _text_93:any;
  _el_94:any;
  _text_95:any;
  _text_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _text_100:any;
  _el_101:any;
  _text_102:any;
  _text_103:any;
  _el_104:any;
  _text_105:any;
  _text_106:any;
  _el_107:any;
  _text_108:any;
  _text_109:any;
  _el_110:any;
  _text_111:any;
  _text_112:any;
  _el_113:any;
  _text_114:any;
  _text_115:any;
  _el_116:any;
  _text_117:any;
  _text_118:any;
  _el_119:any;
  _text_120:any;
  _text_121:any;
  _el_122:any;
  _text_123:any;
  _text_124:any;
  _el_125:any;
  _text_126:any;
  _text_127:any;
  _el_128:any;
  _text_129:any;
  _el_130:any;
  _text_131:any;
  _text_132:any;
  _text_133:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PrivacyPolicyComponent0,renderType_PrivacyPolicyComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'pm-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import10.View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new import10.Wrapper_HeaderComponent();
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'legalMenu',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_4 = new import12.View_LegalMenuComponent0(this.viewUtils,this,4,this._el_4);
    this._LegalMenuComponent_4_3 = new import12.Wrapper_LegalMenuComponent();
    this.compView_4.create(this._LegalMenuComponent_4_3.context);
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','body'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Slamby website privacy policy',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_6,'p',new import3.InlineArray2(2,'class','lead'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Legal information & notices',(null as any));
    this._text_13 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'General',(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Slamby operates https://www.slamby.com, https://developers.slamby.com (the "Sites"). This page informs you of our policies regarding the collection, use and disclosure of Personal Information we receive from users of the Sites.',(null as any));
    this._text_19 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'We use your Personal or Company Information only for providing and improving the Sites, our products, and our services. By using the Sites, you agree to the collection and use of information in accordance with this policy.',(null as any));
    this._text_22 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Information collection and use',(null as any));
    this._text_25 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'While using our Site, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally, identifiable information may include but is not limited to your name ("Personal Information").',(null as any));
    this._text_28 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'We collect information from you when you register on our site, subscribe to our newsletter or fill out any online form.',(null as any));
    this._text_31 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'When ordering or registering on our site, as appropriate, you may be asked to enter your: name, e-mail address, company/business details or mailing address. You may, however, visit our site anonymously.',(null as any));
    this._text_34 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'What information do we collect?',(null as any));
    this._text_37 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'We collect information from you when you register on our site, subscribe to our newsletter or fill out any online form.',(null as any));
    this._text_40 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'When ordering or registering on our site, as appropriate, you may be asked to enter your: name, e-mail address, company/business details or mailing address. You may, however, visit our site anonymously.',(null as any));
    this._text_43 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'Log data',(null as any));
    this._text_46 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'Like many site operators, we collect information that your browser sends whenever you visit our Site ("Log Data"). This Log Data may include information such as your computer\'s Internet Protocol ("IP") address, browser type, browser version, the pages of our Site that you visit, the time and date of your visit, the time spent on those pages and other statistics.',(null as any));
    this._text_49 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'In addition, we may use third-party services such as Google Analytics that collect, monitor and analyze this data.',(null as any));
    this._text_52 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'Communications',(null as any));
    this._text_55 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'We may use your Personal Information to contact you with newsletters, marketing or promotional materials.',(null as any));
    this._text_58 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'Do we use cookies?',(null as any));
    this._text_61 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'Yes, we do. Cookies are files with small amount of data, which may include an anonymous unique identifier.',(null as any));
    this._text_64 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'Cookies are sent to your browser from a website and stored on your computer\'s hard drive.',(null as any));
    this._text_67 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'Like many sites, we use "cookies" to collect information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Site.',(null as any));
    this._text_70 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'How do we use the collected data?',(null as any));
    this._text_73 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'Any collected information from you may be used in one of the following ways:',(null as any));
    this._text_76 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_6,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_78 = this.renderer.createText(this._el_77,'\n            ',(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,this._el_77,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'To personalize your experience',(null as any));
    this._text_81 = this.renderer.createText(this._el_77,'\n            ',(null as any));
    this._el_82 = import3.createRenderElement(this.renderer,this._el_77,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_83 = this.renderer.createText(this._el_82,'To improve our websites',(null as any));
    this._text_84 = this.renderer.createText(this._el_77,'\n            ',(null as any));
    this._el_85 = import3.createRenderElement(this.renderer,this._el_77,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_86 = this.renderer.createText(this._el_85,'To improve customer service',(null as any));
    this._text_87 = this.renderer.createText(this._el_77,'\n            ',(null as any));
    this._el_88 = import3.createRenderElement(this.renderer,this._el_77,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_89 = this.renderer.createText(this._el_88,'To automated emails for administrative purpose',(null as any));
    this._text_90 = this.renderer.createText(this._el_77,'\n            ',(null as any));
    this._el_91 = import3.createRenderElement(this.renderer,this._el_77,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_92 = this.renderer.createText(this._el_91,'To send surveys, or promotion emails',(null as any));
    this._text_93 = this.renderer.createText(this._el_77,'\n            ',(null as any));
    this._el_94 = import3.createRenderElement(this.renderer,this._el_77,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_95 = this.renderer.createText(this._el_94,'To send newsletters',(null as any));
    this._text_96 = this.renderer.createText(this._el_77,'\n        ',(null as any));
    this._text_97 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_98 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_99 = this.renderer.createText(this._el_98,'Your provided email address may be used to send you information, respond to inquiries.',(null as any));
    this._text_100 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_101 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_102 = this.renderer.createText(this._el_101,'Security',(null as any));
    this._text_103 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_104 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_105 = this.renderer.createText(this._el_104,'The security of your Personal Information is important to us, but remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security.',(null as any));
    this._text_106 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_107 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_108 = this.renderer.createText(this._el_107,'Changes',(null as any));
    this._text_109 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_110 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_111 = this.renderer.createText(this._el_110,'This Privacy Policy is effective as of (add date) and will remain in effect except with respect to any changes in its provisions in the future, which will be in effect immediately after being posted on this page.',(null as any));
    this._text_112 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_113 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_114 = this.renderer.createText(this._el_113,'We reserve the right to update or change our Privacy Policy at any time and you should check this Privacy Policy periodically. Your continued use of the Service after we post any modifications to the Privacy Policy on this page will constitute your acknowledgment of the modifications and your consent to abide and be bound by the modified Privacy Policy.',(null as any));
    this._text_115 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_116 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_117 = this.renderer.createText(this._el_116,'If we make any material changes to this Privacy Policy, we will notify you either through the email address you have provided us or by placing a prominent notice on our website.',(null as any));
    this._text_118 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_119 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_120 = this.renderer.createText(this._el_119,'Consent',(null as any));
    this._text_121 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_122 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_123 = this.renderer.createText(this._el_122,'By using our Sites, you consent to our privacy policy.',(null as any));
    this._text_124 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_125 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_126 = this.renderer.createText(this._el_125,'Contact us',(null as any));
    this._text_127 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_128 = import3.createRenderElement(this.renderer,this._el_6,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_129 = this.renderer.createText(this._el_128,'If you have any questions about this Privacy Policy, please contact us. ',(null as any));
    this._el_130 = import3.createRenderElement(this.renderer,this._el_128,'a',new import3.InlineArray2(2,'href','mailto:hello@slamby.com'),(null as any));
    this._text_131 = this.renderer.createText(this._el_130,'hello@slamby.com',(null as any));
    this._text_132 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_133 = this.renderer.createText(this._el_2,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._text_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._text_100,
      this._el_101,
      this._text_102,
      this._text_103,
      this._el_104,
      this._text_105,
      this._text_106,
      this._el_107,
      this._text_108,
      this._text_109,
      this._el_110,
      this._text_111,
      this._text_112,
      this._el_113,
      this._text_114,
      this._text_115,
      this._el_116,
      this._text_117,
      this._text_118,
      this._el_119,
      this._text_120,
      this._text_121,
      this._el_122,
      this._text_123,
      this._text_124,
      this._el_125,
      this._text_126,
      this._text_127,
      this._el_128,
      this._text_129,
      this._el_130,
      this._text_131,
      this._text_132,
      this._text_133
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    if (((token === import11.LegalMenuComponent) && (4 === requestNodeIndex))) { return this._LegalMenuComponent_4_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._LegalMenuComponent_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
    this.compView_4.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this.compView_4.destroy();
  }
}