/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './pricing.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './pricing.component.css.shim';
import * as import9 from '../common/header/header.component';
import * as import10 from '../common/header/header.component.ngfactory';
import * as import11 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import14 from '@angular/router/src/router';
import * as import15 from '@angular/router/src/router_state';
import * as import16 from '@angular/common/src/location/location_strategy';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import19 from '@angular/router/src/directives/router_link';
import * as import20 from '@angular/common/src/directives/ng_for';
export class Wrapper_PricingComponent {
  /*private*/ _eventHandler:Function;
  context:import0.PricingComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.PricingComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_PricingComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_PricingComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.PricingComponent>;
  _PricingComponent_0_3:Wrapper_PricingComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PricingComponent_Host0,renderType_PricingComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_PricingComponent0(this.viewUtils,this,0,this._el_0);
    this._PricingComponent_0_3 = new Wrapper_PricingComponent();
    this.compView_0.create(this._PricingComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._PricingComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PricingComponent) && (0 === requestNodeIndex))) { return this._PricingComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PricingComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const PricingComponentNgFactory:import7.ComponentFactory<import0.PricingComponent> = new import7.ComponentFactory<import0.PricingComponent>('ng-component',View_PricingComponent_Host0,import0.PricingComponent);
const styles_PricingComponent:any[] = [import8.styles];
var renderType_PricingComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_PricingComponent,{});
export class View_PricingComponent0 extends import1.AppView<import0.PricingComponent> {
  _el_0:any;
  compView_0:import1.AppView<import9.HeaderComponent>;
  _HeaderComponent_0_3:import10.Wrapper_HeaderComponent;
  _el_1:any;
  _el_2:any;
  _el_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _el_12:any;
  _RouterLinkWithHref_12_3:import11.Wrapper_RouterLinkWithHref;
  _text_13:any;
  _el_14:any;
  _el_15:any;
  _el_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _el_26:any;
  _el_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _el_34:any;
  _el_35:any;
  _el_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _el_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _el_52:any;
  _el_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _el_69:any;
  _el_70:any;
  _el_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _el_78:any;
  _el_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _el_83:any;
  _text_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _el_88:any;
  _el_89:any;
  _text_90:any;
  _el_91:any;
  _text_92:any;
  _el_93:any;
  _text_94:any;
  _el_95:any;
  _el_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _el_102:any;
  _el_103:any;
  _el_104:any;
  _el_105:any;
  _text_106:any;
  _el_107:any;
  _text_108:any;
  _el_109:any;
  _el_110:any;
  _text_111:any;
  _el_112:any;
  _text_113:any;
  _el_114:any;
  _text_115:any;
  _el_116:any;
  _el_117:any;
  _el_118:any;
  _el_119:any;
  _text_120:any;
  _el_121:any;
  _text_122:any;
  _el_123:any;
  _text_124:any;
  _el_125:any;
  _text_126:any;
  _el_127:any;
  _text_128:any;
  _el_129:any;
  _text_130:any;
  _el_131:any;
  _text_132:any;
  _el_133:any;
  _anchor_134:any;
  /*private*/ _vc_134:import12.ViewContainer;
  _TemplateRef_134_5:any;
  _NgFor_134_6:import13.Wrapper_NgFor;
  _el_135:any;
  _el_136:any;
  _el_137:any;
  _text_138:any;
  _el_139:any;
  _el_140:any;
  _el_141:any;
  _el_142:any;
  _text_143:any;
  _el_144:any;
  _text_145:any;
  _el_146:any;
  _text_147:any;
  _el_148:any;
  _text_149:any;
  _el_150:any;
  _text_151:any;
  _el_152:any;
  _text_153:any;
  _el_154:any;
  _text_155:any;
  _el_156:any;
  _anchor_157:any;
  /*private*/ _vc_157:import12.ViewContainer;
  _TemplateRef_157_5:any;
  _NgFor_157_6:import13.Wrapper_NgFor;
  _arr_167:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PricingComponent0,renderType_PricingComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._arr_167 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'pm-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import10.View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new import10.Wrapper_HeaderComponent();
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'section',new import3.InlineArray2(2,'class','main'),(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','body'),(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','main-message'),(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_4,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'45 € / core / month',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_4,'p',new import3.InlineArray2(2,'class','lead'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Start using Slamby for a price of a cup of coffee per core. Use it as a SaaS or install it on your machine.',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_4,'p',new import3.InlineArray2(2,'class','lead'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'No query limit, no memory limit',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_4,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_11,'a',new import3.InlineArray8(8,'angulartics2On','click','angularticsCategory','pricing-page','angularticsEvent','getting-started-click','class','btn btn-default btn-lg'),(null as any));
    this._RouterLinkWithHref_12_3 = new import11.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import14.Router,this.parentIndex),this.parentView.injectorGet(import15.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import16.LocationStrategy,this.parentIndex));
    this._text_13 = this.renderer.createText(this._el_12,'Getting started',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_14,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_16,'h1',new import3.InlineArray2(2,'class','page-header'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Pricing',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_16,'p',new import3.InlineArray2(2,'class','lead'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Our product is available for both private hosting and SaaS. You can easily download and install it on your machine, or purchase it as a monthly service.',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_16,'p',new import3.InlineArray2(2,'class','lead'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'For private hosting, you can download and install Slamby API and register it with an open-source license for free, and you can purchase a core-based license for commercial use.',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_16,'p',new import3.InlineArray2(2,'class','lead'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'For SaaS, you can select a required instance size and buy it with a monthly payment. The prices cover the standard Slamby license per core + hosting fee.',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_25,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_26,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_27,'h1',new import3.InlineArray2(2,'class','page-header'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Core pricing',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_26,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_30,'p',new import3.InlineArray2(2,'class','lead'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Standard Slamby API pricing, based on the  processor core number. There is no query, usage, storage and memory limitation.',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_26,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_33,'table',new import3.InlineArray2(2,'class','table table-striped'),(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_34,'thead',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_35,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_36,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Name',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_36,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Description',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_36,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'price',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_34,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_43,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_44,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'1 core license',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_44,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'unlimited memory, unlimited storage',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_44,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'45 € / processor core / month',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_51,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_52,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_53,'h2',new import3.InlineArray2(2,'class','page-header'),(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'Support',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_52,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_56,'p',new import3.InlineArray2(2,'class','lead'),(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'For professional use select one of our available support options based on the available communication channels and SLA.',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_56,'p',new import3.InlineArray2(2,'class','lead'),(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'Currently, we have three type of support options. Each Slamby instance has a basic support option that includes community-based - forum support.',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_56,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_61,'a',new import3.InlineArray8(8,'angulartics2On','click','angularticsCategory','pricing-page','angularticsEvent','support-get-mode-information','href','mailto:sales@slamby.com'),(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'Get more information',(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,this._el_56,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'Community support:',(null as any));
    this._el_66 = import3.createRenderElement(this.renderer,this._el_64,'a',new import3.InlineArray4(4,'href','https://groups.google.com/forum/#!forum/slamby','target','_blank'),(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'https://groups.google.com/forum/#!forum/slamby',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_52,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._el_69 = import3.createRenderElement(this.renderer,this._el_68,'table',new import3.InlineArray2(2,'class','table table-striped'),(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_69,'thead',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_70,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_72 = import3.createRenderElement(this.renderer,this._el_71,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'Name',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_71,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'Description',(null as any));
    this._el_76 = import3.createRenderElement(this.renderer,this._el_71,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_77 = this.renderer.createText(this._el_76,'price',(null as any));
    this._el_78 = import3.createRenderElement(this.renderer,this._el_69,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,this._el_78,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_80 = import3.createRenderElement(this.renderer,this._el_79,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_81 = this.renderer.createText(this._el_80,'Basic',(null as any));
    this._el_82 = import3.createRenderElement(this.renderer,this._el_79,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_83 = import3.createRenderElement(this.renderer,this._el_82,'a',new import3.InlineArray4(4,'href','https://groups.google.com/forum/#!forum/slamby','target','_blank'),(null as any));
    this._text_84 = this.renderer.createText(this._el_83,'Community only',(null as any));
    this._text_85 = this.renderer.createText(this._el_82,',no SLA',(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_79,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_87 = this.renderer.createText(this._el_86,'Free',(null as any));
    this._el_88 = import3.createRenderElement(this.renderer,this._el_78,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_89 = import3.createRenderElement(this.renderer,this._el_88,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'Professional',(null as any));
    this._el_91 = import3.createRenderElement(this.renderer,this._el_88,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_92 = this.renderer.createText(this._el_91,'Next workday, email',(null as any));
    this._el_93 = import3.createRenderElement(this.renderer,this._el_88,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_94 = this.renderer.createText(this._el_93,'2000 € yearly / instance',(null as any));
    this._el_95 = import3.createRenderElement(this.renderer,this._el_78,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_96 = import3.createRenderElement(this.renderer,this._el_95,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_97 = this.renderer.createText(this._el_96,'Production',(null as any));
    this._el_98 = import3.createRenderElement(this.renderer,this._el_95,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_99 = this.renderer.createText(this._el_98,'Direct developer and technical access, 5 hours SLA, email, skype, phone.',(null as any));
    this._el_100 = import3.createRenderElement(this.renderer,this._el_95,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_101 = this.renderer.createText(this._el_100,'6000 € yearly / instance',(null as any));
    this._el_102 = import3.createRenderElement(this.renderer,this._el_52,'div',new import3.InlineArray2(2,'class','container pricing'),(null as any));
    this._el_103 = import3.createRenderElement(this.renderer,this._el_102,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._el_104 = import3.createRenderElement(this.renderer,this._el_103,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._el_105 = import3.createRenderElement(this.renderer,this._el_104,'h2',new import3.InlineArray2(2,'class','page-header'),(null as any));
    this._text_106 = this.renderer.createText(this._el_105,'SaaS pricing',(null as any));
    this._el_107 = import3.createRenderElement(this.renderer,this._el_104,'p',new import3.InlineArray2(2,'class','lead'),(null as any));
    this._text_108 = this.renderer.createText(this._el_107,'Purchase Slamby as software as a service. Select one of our hosting locations and one suitable size of the instance. Prices based on the resource size + core based Slamby license fee.',(null as any));
    this._el_109 = import3.createRenderElement(this.renderer,this._el_104,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_110 = import3.createRenderElement(this.renderer,this._el_109,'a',new import3.InlineArray16(10,'angulartics2On','click','angularticsCategory','pricing-page','angularticsEvent','sas-contact-sales','class','btn btn-default','href','mailto:sales@slamby.com'),(null as any));
    this._text_111 = this.renderer.createText(this._el_110,'Contact sales',(null as any));
    this._el_112 = import3.createRenderElement(this.renderer,this._el_104,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_113 = this.renderer.createText(this._el_112,'Prices are in € per month',(null as any));
    this._el_114 = import3.createRenderElement(this.renderer,this._el_104,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_115 = this.renderer.createText(this._el_114,'European',(null as any));
    this._el_116 = import3.createRenderElement(this.renderer,this._el_104,'table',new import3.InlineArray2(2,'class','table table-striped'),(null as any));
    this._el_117 = import3.createRenderElement(this.renderer,this._el_116,'thead',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_118 = import3.createRenderElement(this.renderer,this._el_117,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_119 = import3.createRenderElement(this.renderer,this._el_118,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_120 = this.renderer.createText(this._el_119,'Name',(null as any));
    this._el_121 = import3.createRenderElement(this.renderer,this._el_118,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_122 = this.renderer.createText(this._el_121,'Core',(null as any));
    this._el_123 = import3.createRenderElement(this.renderer,this._el_118,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_124 = this.renderer.createText(this._el_123,'Memory',(null as any));
    this._el_125 = import3.createRenderElement(this.renderer,this._el_118,'th',new import3.InlineArray2(2,'class','hidden-xs'),(null as any));
    this._text_126 = this.renderer.createText(this._el_125,'Storage',(null as any));
    this._el_127 = import3.createRenderElement(this.renderer,this._el_118,'th',new import3.InlineArray2(2,'class','hidden-xs hiddne-sm'),(null as any));
    this._text_128 = this.renderer.createText(this._el_127,'Technical fee',(null as any));
    this._el_129 = import3.createRenderElement(this.renderer,this._el_118,'th',new import3.InlineArray2(2,'class','hidden-xs hidden-sm'),(null as any));
    this._text_130 = this.renderer.createText(this._el_129,'License fee',(null as any));
    this._el_131 = import3.createRenderElement(this.renderer,this._el_118,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_132 = this.renderer.createText(this._el_131,'Retail price',(null as any));
    this._el_133 = import3.createRenderElement(this.renderer,this._el_116,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._anchor_134 = this.renderer.createTemplateAnchor(this._el_133,(null as any));
    this._vc_134 = new import12.ViewContainer(134,133,this,this._anchor_134);
    this._TemplateRef_134_5 = new import17.TemplateRef_(this,134,this._anchor_134);
    this._NgFor_134_6 = new import13.Wrapper_NgFor(this._vc_134.vcRef,this._TemplateRef_134_5,this.parentView.injectorGet(import18.IterableDiffers,this.parentIndex),this.ref);
    this._el_135 = import3.createRenderElement(this.renderer,this._el_102,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._el_136 = import3.createRenderElement(this.renderer,this._el_135,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._el_137 = import3.createRenderElement(this.renderer,this._el_136,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_138 = this.renderer.createText(this._el_137,'Asian',(null as any));
    this._el_139 = import3.createRenderElement(this.renderer,this._el_136,'table',new import3.InlineArray2(2,'class','table table-striped'),(null as any));
    this._el_140 = import3.createRenderElement(this.renderer,this._el_139,'thead',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_141 = import3.createRenderElement(this.renderer,this._el_140,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_142 = import3.createRenderElement(this.renderer,this._el_141,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_143 = this.renderer.createText(this._el_142,'Name',(null as any));
    this._el_144 = import3.createRenderElement(this.renderer,this._el_141,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_145 = this.renderer.createText(this._el_144,'Core',(null as any));
    this._el_146 = import3.createRenderElement(this.renderer,this._el_141,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_147 = this.renderer.createText(this._el_146,'Memory',(null as any));
    this._el_148 = import3.createRenderElement(this.renderer,this._el_141,'th',new import3.InlineArray2(2,'class','hidden-xs'),(null as any));
    this._text_149 = this.renderer.createText(this._el_148,'Storage',(null as any));
    this._el_150 = import3.createRenderElement(this.renderer,this._el_141,'th',new import3.InlineArray2(2,'class','hidden-xs hiddne-sm'),(null as any));
    this._text_151 = this.renderer.createText(this._el_150,'Technical fee',(null as any));
    this._el_152 = import3.createRenderElement(this.renderer,this._el_141,'th',new import3.InlineArray2(2,'class','hidden-xs hidden-sm'),(null as any));
    this._text_153 = this.renderer.createText(this._el_152,'License fee',(null as any));
    this._el_154 = import3.createRenderElement(this.renderer,this._el_141,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_155 = this.renderer.createText(this._el_154,'Retail price',(null as any));
    this._el_156 = import3.createRenderElement(this.renderer,this._el_139,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._anchor_157 = this.renderer.createTemplateAnchor(this._el_156,(null as any));
    this._vc_157 = new import12.ViewContainer(157,156,this,this._anchor_157);
    this._TemplateRef_157_5 = new import17.TemplateRef_(this,157,this._anchor_157);
    this._NgFor_157_6 = new import13.Wrapper_NgFor(this._vc_157.vcRef,this._TemplateRef_157_5,this.parentView.injectorGet(import18.IterableDiffers,this.parentIndex),this.ref);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_12,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_12));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._el_2,
      this._el_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._el_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._el_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._el_34,
      this._el_35,
      this._el_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._el_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._el_52,
      this._el_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._el_69,
      this._el_70,
      this._el_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._el_78,
      this._el_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._el_83,
      this._text_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._el_88,
      this._el_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._el_95,
      this._el_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._el_102,
      this._el_103,
      this._el_104,
      this._el_105,
      this._text_106,
      this._el_107,
      this._text_108,
      this._el_109,
      this._el_110,
      this._text_111,
      this._el_112,
      this._text_113,
      this._el_114,
      this._text_115,
      this._el_116,
      this._el_117,
      this._el_118,
      this._el_119,
      this._text_120,
      this._el_121,
      this._text_122,
      this._el_123,
      this._text_124,
      this._el_125,
      this._text_126,
      this._el_127,
      this._text_128,
      this._el_129,
      this._text_130,
      this._el_131,
      this._text_132,
      this._el_133,
      this._anchor_134,
      this._el_135,
      this._el_136,
      this._el_137,
      this._text_138,
      this._el_139,
      this._el_140,
      this._el_141,
      this._el_142,
      this._text_143,
      this._el_144,
      this._text_145,
      this._el_146,
      this._text_147,
      this._el_148,
      this._text_149,
      this._el_150,
      this._text_151,
      this._el_152,
      this._text_153,
      this._el_154,
      this._text_155,
      this._el_156,
      this._anchor_157
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    if (((token === import19.RouterLinkWithHref) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._RouterLinkWithHref_12_3.context; }
    if (((token === import17.TemplateRef) && (134 === requestNodeIndex))) { return this._TemplateRef_134_5; }
    if (((token === import20.NgFor) && (134 === requestNodeIndex))) { return this._NgFor_134_6.context; }
    if (((token === import17.TemplateRef) && (157 === requestNodeIndex))) { return this._TemplateRef_157_5; }
    if (((token === import20.NgFor) && (157 === requestNodeIndex))) { return this._NgFor_157_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_12_0_0:any = this._arr_167('/getting-started');
    this._RouterLinkWithHref_12_3.check_routerLink(currVal_12_0_0,throwOnChange,false);
    this._RouterLinkWithHref_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_134_0_0:any = this.context.pricingEurope;
    this._NgFor_134_6.check_ngForOf(currVal_134_0_0,throwOnChange,false);
    this._NgFor_134_6.ngDoCheck(this,this._anchor_134,throwOnChange);
    const currVal_157_0_0:any = this.context.pricingAsian;
    this._NgFor_157_6.check_ngForOf(currVal_157_0_0,throwOnChange,false);
    this._NgFor_157_6.ngDoCheck(this,this._anchor_157,throwOnChange);
    this._vc_134.detectChangesInNestedViews(throwOnChange);
    this._vc_157.detectChangesInNestedViews(throwOnChange);
    this._RouterLinkWithHref_12_3.checkHost(this,this,this._el_12,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_134.destroyNestedViews();
    this._vc_157.destroyNestedViews();
    this.compView_0.destroy();
    this._RouterLinkWithHref_12_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 134)) { return new View_PricingComponent1(this.viewUtils,this,134,this._anchor_134,this._vc_134); }
    if ((nodeIndex == 157)) { return new View_PricingComponent2(this.viewUtils,this,157,this._anchor_157,this._vc_157); }
    return (null as any);
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_12_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_PricingComponent1 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_PricingComponent1,renderType_PricingComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_15 = import6.UNINITIALIZED;
    this._expr_16 = import6.UNINITIALIZED;
    this._expr_17 = import6.UNINITIALIZED;
    this._expr_18 = import6.UNINITIALIZED;
    this._expr_19 = import6.UNINITIALIZED;
    this._expr_20 = import6.UNINITIALIZED;
    this._expr_21 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'td',new import3.InlineArray2(2,'class','hidden-xs'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_0,'td',new import3.InlineArray2(2,'class','hidden-xs hidden-sm'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_0,'td',new import3.InlineArray2(2,'class','hidden-xs hidden-sm'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_15:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setText(this._text_2,currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = import3.inlineInterpolate(1,'',this.context.$implicit.core,'');
    if (import3.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setText(this._text_4,currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = import3.inlineInterpolate(1,'',this.context.$implicit.memory,'');
    if (import3.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setText(this._text_6,currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = import3.inlineInterpolate(1,'',this.context.$implicit.storage,'');
    if (import3.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setText(this._text_8,currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = import3.inlineInterpolate(1,'',this.context.$implicit.technicalFee,' €');
    if (import3.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setText(this._text_10,currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = import3.inlineInterpolate(1,'',this.context.$implicit.slambyLicenseFee,' €');
    if (import3.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setText(this._text_12,currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = import3.inlineInterpolate(1,'',this.context.$implicit.retailPrice,' €');
    if (import3.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setText(this._text_14,currVal_21);
      this._expr_21 = currVal_21;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_PricingComponent2 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_PricingComponent2,renderType_PricingComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_15 = import6.UNINITIALIZED;
    this._expr_16 = import6.UNINITIALIZED;
    this._expr_17 = import6.UNINITIALIZED;
    this._expr_18 = import6.UNINITIALIZED;
    this._expr_19 = import6.UNINITIALIZED;
    this._expr_20 = import6.UNINITIALIZED;
    this._expr_21 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'td',new import3.InlineArray2(2,'class','hidden-xs'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_0,'td',new import3.InlineArray2(2,'class','hidden-xs hidden-sm'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_0,'td',new import3.InlineArray2(2,'class','hidden-xs hidden-sm'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_15:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setText(this._text_2,currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = import3.inlineInterpolate(1,'',this.context.$implicit.core,'');
    if (import3.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setText(this._text_4,currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = import3.inlineInterpolate(1,'',this.context.$implicit.memory,'');
    if (import3.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setText(this._text_6,currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = import3.inlineInterpolate(1,'',this.context.$implicit.storage,'');
    if (import3.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setText(this._text_8,currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = import3.inlineInterpolate(1,'',this.context.$implicit.technicalFee,' €');
    if (import3.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setText(this._text_10,currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = import3.inlineInterpolate(1,'',this.context.$implicit.slambyLicenseFee,' €');
    if (import3.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setText(this._text_12,currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = import3.inlineInterpolate(1,'',this.context.$implicit.retailPrice,' €');
    if (import3.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setText(this._text_14,currVal_21);
      this._expr_21 = currVal_21;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}