/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.notFoundModule[_ngcontent-%COMP%]{text-align:center}.notFoundModule[_ngcontent-%COMP%]   .box[_ngcontent-%COMP%]{margin-top:50px}.notFoundModule[_ngcontent-%COMP%]   .box[_ngcontent-%COMP%]   .icon[_ngcontent-%COMP%]   i[_ngcontent-%COMP%]{font-size:70px;font-weight:100}'];