/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './getting-started.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './getting-started.component.css.shim';
import * as import9 from '../common/header/header.component';
import * as import10 from '../common/header/header.component.ngfactory';
export class Wrapper_GettingStartedComponent {
  /*private*/ _eventHandler:Function;
  context:import0.GettingStartedComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.GettingStartedComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_GettingStartedComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_GettingStartedComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.GettingStartedComponent>;
  _GettingStartedComponent_0_3:Wrapper_GettingStartedComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_GettingStartedComponent_Host0,renderType_GettingStartedComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_GettingStartedComponent0(this.viewUtils,this,0,this._el_0);
    this._GettingStartedComponent_0_3 = new Wrapper_GettingStartedComponent();
    this.compView_0.create(this._GettingStartedComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._GettingStartedComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.GettingStartedComponent) && (0 === requestNodeIndex))) { return this._GettingStartedComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._GettingStartedComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const GettingStartedComponentNgFactory:import7.ComponentFactory<import0.GettingStartedComponent> = new import7.ComponentFactory<import0.GettingStartedComponent>('ng-component',View_GettingStartedComponent_Host0,import0.GettingStartedComponent);
const styles_GettingStartedComponent:any[] = [import8.styles];
var renderType_GettingStartedComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_GettingStartedComponent,{});
export class View_GettingStartedComponent0 extends import1.AppView<import0.GettingStartedComponent> {
  _el_0:any;
  compView_0:import1.AppView<import9.HeaderComponent>;
  _HeaderComponent_0_3:import10.Wrapper_HeaderComponent;
  _el_1:any;
  _el_2:any;
  _el_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_GettingStartedComponent0,renderType_GettingStartedComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'pm-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import10.View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new import10.Wrapper_HeaderComponent();
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','menu'),(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','list-group'),(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_3,'a',new import3.InlineArray8(6,'class','list-group-item','href','#api-install','pageScroll','pageScroll'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'API install',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_3,'a',new import3.InlineArray8(6,'class','list-group-item','href','#api-activation','pageScroll','pageScroll'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'API activation',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_3,'a',new import3.InlineArray8(6,'class','list-group-item','href','#slamby-insight','pageScroll','pageScroll'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Slamby Insight',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_3,'a',new import3.InlineArray8(6,'class','list-group-item','href','#integration','pageScroll','pageScroll'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Integration',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_3,'a',new import3.InlineArray8(6,'class','list-group-item','href','#documentation','pageScroll','pageScroll'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Documentation',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_3,'a',new import3.InlineArray8(6,'class','list-group-item','href','#support','pageScroll','pageScroll'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'Support',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','body'),(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_16,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Getting started',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_16,'p',new import3.InlineArray2(2,'class','lead'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Welcome to Slamby. Congratulation, you made the very first step to work with our awesome products. You are almost done, but before getting started working with your Slamby product, here are a few useful information.',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_16,'h2',new import3.InlineArray2(2,'id','api-install'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'API install',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_16,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'You can use your Slamby API as a SaaS, or you can download, and host is by yourself. When you want to host it by yourself, the first thing you need to manage is the installation. To install Slamby API, please check the product readme and the installation guide.',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_16,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'Product documentation:',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'a',new import3.InlineArray4(4,'href','https://github.com/slamby/slamby-api','target','_blank'),(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_16,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Using Docker Compose, here are the installation steps:',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_16,'ol',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_30,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Install Docker on your machine:',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_31,'a',new import3.InlineArray4(4,'href','https://docs.docker.com/engine/installation','target','_blank'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'Official Docker installation guide',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._el_2,
      this._el_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
}