/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.container[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]{padding:30px 0px 30px 0px;text-align:center}@media (min-width: 768px){.container[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]{text-align:right}}a[_ngcontent-%COMP%]:not(:last-of-type){margin-right:15px}'];