/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.footer[_ngcontent-%COMP%]{margin-left:-15px;margin-right:-15px}.footer[_ngcontent-%COMP%]:before, .footer[_ngcontent-%COMP%]:after{content:" ";display:table}.footer[_ngcontent-%COMP%]:after{clear:both}.footer[_ngcontent-%COMP%]   .message[_ngcontent-%COMP%]{position:relative;min-height:1px;padding-left:15px;padding-right:15px;padding-top:15px;margin-top:30px;color:grey;font-weight:100}@media (min-width: 768px){.footer[_ngcontent-%COMP%]   .message[_ngcontent-%COMP%]{float:left;width:100%}}.footer[_ngcontent-%COMP%]   .links[_ngcontent-%COMP%]{position:relative;min-height:1px;padding-left:15px;padding-right:15px;margin-top:5px}@media (min-width: 768px){.footer[_ngcontent-%COMP%]   .links[_ngcontent-%COMP%]{float:left;width:100%}}.footer[_ngcontent-%COMP%]   .links[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]{display:inline-block;text-decoration:none;margin:0px 15px 0px 0px;font-weight:100}.footer[_ngcontent-%COMP%]   .sla-external-link[_ngcontent-%COMP%]{padding-left:3px;font-size:10px}'];