/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './footer.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './footer.component.css.shim';
import * as import9 from '../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/router/src/router_state';
import * as import12 from '@angular/common/src/location/location_strategy';
import * as import13 from '@angular/router/src/directives/router_link';
export class Wrapper_FooterComponent {
  /*private*/ _eventHandler:Function;
  context:import0.FooterComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.FooterComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_FooterComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_FooterComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.FooterComponent>;
  _FooterComponent_0_3:Wrapper_FooterComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FooterComponent_Host0,renderType_FooterComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'pm-footer',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_FooterComponent0(this.viewUtils,this,0,this._el_0);
    this._FooterComponent_0_3 = new Wrapper_FooterComponent();
    this.compView_0.create(this._FooterComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._FooterComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.FooterComponent) && (0 === requestNodeIndex))) { return this._FooterComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._FooterComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const FooterComponentNgFactory:import7.ComponentFactory<import0.FooterComponent> = new import7.ComponentFactory<import0.FooterComponent>('pm-footer',View_FooterComponent_Host0,import0.FooterComponent);
const styles_FooterComponent:any[] = [import8.styles];
var renderType_FooterComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_FooterComponent,{});
export class View_FooterComponent0 extends import1.AppView<import0.FooterComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _el_20:any;
  _RouterLinkWithHref_20_3:import9.Wrapper_RouterLinkWithHref;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _el_24:any;
  _RouterLinkWithHref_24_3:import9.Wrapper_RouterLinkWithHref;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _el_28:any;
  _RouterLinkWithHref_28_3:import9.Wrapper_RouterLinkWithHref;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _arr_36:any;
  _arr_37:any;
  _arr_38:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FooterComponent0,renderType_FooterComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._arr_36 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_37 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_38 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','footer'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','message'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Slamby 2016',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'ul',new import3.InlineArray2(2,'class','links'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_9,'a',new import3.InlineArray4(4,'href','https://github.com/slamby','target','_blank'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Github ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-external-link sla-external-link'),(null as any));
    this._text_13 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_7,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_14,'a',new import3.InlineArray4(4,'href','https://developers.slamby.com','target','_blank'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Slamby Developers ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-external-link sla-external-link'),(null as any));
    this._text_18 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_7,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_19,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_20_3 = new import9.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import10.Router,this.parentIndex),this.parentView.injectorGet(import11.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import12.LocationStrategy,this.parentIndex));
    this._text_21 = this.renderer.createText(this._el_20,'Partners',(null as any));
    this._text_22 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_7,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_23,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_24_3 = new import9.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import10.Router,this.parentIndex),this.parentView.injectorGet(import11.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import12.LocationStrategy,this.parentIndex));
    this._text_25 = this.renderer.createText(this._el_24,'Company',(null as any));
    this._text_26 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_7,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_27,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_28_3 = new import9.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import10.Router,this.parentIndex),this.parentView.injectorGet(import11.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import12.LocationStrategy,this.parentIndex));
    this._text_29 = this.renderer.createText(this._el_28,'Legal',(null as any));
    this._text_30 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._text_31 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_32 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_20,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_20));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_24,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_24));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_28,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_28));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._RouterLinkWithHref_20_3.context; }
    if (((token === import13.RouterLinkWithHref) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._RouterLinkWithHref_24_3.context; }
    if (((token === import13.RouterLinkWithHref) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._RouterLinkWithHref_28_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_20_0_0:any = this._arr_36('/partners');
    this._RouterLinkWithHref_20_3.check_routerLink(currVal_20_0_0,throwOnChange,false);
    this._RouterLinkWithHref_20_3.ngDoCheck(this,this._el_20,throwOnChange);
    const currVal_24_0_0:any = this._arr_37('/company');
    this._RouterLinkWithHref_24_3.check_routerLink(currVal_24_0_0,throwOnChange,false);
    this._RouterLinkWithHref_24_3.ngDoCheck(this,this._el_24,throwOnChange);
    const currVal_28_0_0:any = this._arr_38('/legal/privacy-policy');
    this._RouterLinkWithHref_28_3.check_routerLink(currVal_28_0_0,throwOnChange,false);
    this._RouterLinkWithHref_28_3.ngDoCheck(this,this._el_28,throwOnChange);
    this._RouterLinkWithHref_20_3.checkHost(this,this,this._el_20,throwOnChange);
    this._RouterLinkWithHref_24_3.checkHost(this,this,this._el_24,throwOnChange);
    this._RouterLinkWithHref_28_3.checkHost(this,this,this._el_28,throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_20_3.ngOnDestroy();
    this._RouterLinkWithHref_24_3.ngOnDestroy();
    this._RouterLinkWithHref_28_3.ngOnDestroy();
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_20_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_24(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_24_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_28(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_28_3.handleEvent(eventName,$event) && result);
    return result;
  }
}