/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/router/src/router_module';
import * as import6 from '@angular/common/src/localization';
import * as import7 from '@angular/core/src/application_init';
import * as import8 from '@angular/core/src/testability/testability';
import * as import9 from '@angular/core/src/application_ref';
import * as import10 from '@angular/core/src/linker/compiler';
import * as import11 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import12 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import13 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import14 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import15 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import16 from '@angular/core/src/linker/view_utils';
import * as import17 from '@angular/platform-browser/src/browser/title';
import * as import18 from '@angular/common/src/location/location';
import * as import19 from '@angular/router/src/url_tree';
import * as import20 from '@angular/router/src/router_outlet_map';
import * as import21 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import22 from '@angular/core/src/di/injector';
import * as import23 from './home/home.component.ngfactory';
import * as import24 from './insight/insight.component.ngfactory';
import * as import25 from './pricing/pricing.component.ngfactory';
import * as import26 from './404/404.component.ngfactory';
import * as import27 from './thank-you/thank-you.component.ngfactory';
import * as import28 from './getting-started/getting-started.component.ngfactory';
import * as import29 from './partners/partners.component.ngfactory';
import * as import30 from './company/company.component.ngfactory';
import * as import31 from './legal/privacy-policy.component.ngfactory';
import * as import32 from './legal/commercial-license.component.ngfactory';
import * as import33 from './legal/commercial-license-oem.component.ngfactory';
import * as import34 from './legal/gnu-agpl-license.component.ngfactory';
import * as import35 from './legal/open-source-license.component.ngfactory';
import * as import36 from './support/support.component.ngfactory';
import * as import37 from './app.component.ngfactory';
import * as import38 from '@angular/core/src/application_tokens';
import * as import39 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import40 from '@angular/platform-browser/src/dom/events/key_events';
import * as import41 from '@angular/core/src/zone/ng_zone';
import * as import42 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import43 from '@angular/common/src/location/platform_location';
import * as import44 from '@angular/common/src/location/location_strategy';
import * as import45 from './home/home.component';
import * as import46 from './insight/insight.component';
import * as import47 from './pricing/pricing.component';
import * as import48 from './404/404.component';
import * as import49 from './thank-you/thank-you.component';
import * as import50 from './getting-started/getting-started.component';
import * as import51 from './partners/partners.component';
import * as import52 from './company/company.component';
import * as import53 from './legal/privacy-policy.component';
import * as import54 from './legal/commercial-license.component';
import * as import55 from './legal/commercial-license-oem.component';
import * as import56 from './legal/gnu-agpl-license.component';
import * as import57 from './legal/open-source-license.component';
import * as import58 from './support/support.component';
import * as import59 from '@angular/router/src/router';
import * as import60 from '@angular/core/src/console';
import * as import61 from '@angular/core/src/i18n/tokens';
import * as import62 from '@angular/core/src/error_handler';
import * as import63 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import64 from '@angular/platform-browser/src/dom/animation_driver';
import * as import65 from '@angular/core/src/render/api';
import * as import66 from '@angular/core/src/security';
import * as import67 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import68 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import69 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import70 from '@angular/router/src/router_config_loader';
import * as import71 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _ROUTER_FORROOT_GUARD_3:any;
  _RouterModule_4:import5.RouterModule;
  _AppModule_5:import1.AppModule;
  __LOCALE_ID_6:any;
  __NgLocalization_7:import6.NgLocaleLocalization;
  _ErrorHandler_8:any;
  _ApplicationInitStatus_9:import7.ApplicationInitStatus;
  _Testability_10:import8.Testability;
  _ApplicationRef__11:import9.ApplicationRef_;
  __ApplicationRef_12:any;
  __Compiler_13:import10.Compiler;
  __APP_ID_14:any;
  __DOCUMENT_15:any;
  __HAMMER_GESTURE_CONFIG_16:import11.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_17:any[];
  __EventManager_18:import12.EventManager;
  __DomSharedStylesHost_19:import13.DomSharedStylesHost;
  __AnimationDriver_20:any;
  __DomRootRenderer_21:import14.DomRootRenderer_;
  __RootRenderer_22:any;
  __DomSanitizer_23:import15.DomSanitizerImpl;
  __Sanitizer_24:any;
  __ViewUtils_25:import16.ViewUtils;
  __IterableDiffers_26:any;
  __KeyValueDiffers_27:any;
  __SharedStylesHost_28:any;
  __Title_29:import17.Title;
  __ROUTER_CONFIGURATION_30:any;
  __LocationStrategy_31:any;
  __Location_32:import18.Location;
  __UrlSerializer_33:import19.DefaultUrlSerializer;
  __RouterOutletMap_34:import20.RouterOutletMap;
  __NgModuleFactoryLoader_35:import21.SystemJsNgModuleLoader;
  __ROUTES_36:any[];
  __Router_37:any;
  __ActivatedRoute_38:any;
  __APP_BOOTSTRAP_LISTENER_39:any[];
  constructor(parent:import22.Injector) {
    super(parent,[
      import23.HomeComponentNgFactory,
      import23.HomeComponentNgFactory,
      import24.InsightComponentNgFactory,
      import25.PricingComponentNgFactory,
      import26.NotFoundPageComponentNgFactory,
      import27.ThankYouComponentNgFactory,
      import28.GettingStartedComponentNgFactory,
      import29.PartnersComponentNgFactory,
      import30.CompanyComponentNgFactory,
      import31.PrivacyPolicyComponentNgFactory,
      import32.CommercialLicenseComponentNgFactory,
      import33.CommercialLicenseOemComponentNgFactory,
      import34.GnuAgplLicenseComponentNgFactory,
      import35.OpenSourceLicenseComponentNgFactory,
      import36.SupportComponentNgFactory,
      import37.AppComponentNgFactory
    ]
    ,[import37.AppComponentNgFactory]);
  }
  get _LOCALE_ID_6():any {
    if ((this.__LOCALE_ID_6 == null)) { (this.__LOCALE_ID_6 = 'en-US'); }
    return this.__LOCALE_ID_6;
  }
  get _NgLocalization_7():import6.NgLocaleLocalization {
    if ((this.__NgLocalization_7 == null)) { (this.__NgLocalization_7 = new import6.NgLocaleLocalization(this._LOCALE_ID_6)); }
    return this.__NgLocalization_7;
  }
  get _ApplicationRef_12():any {
    if ((this.__ApplicationRef_12 == null)) { (this.__ApplicationRef_12 = this._ApplicationRef__11); }
    return this.__ApplicationRef_12;
  }
  get _Compiler_13():import10.Compiler {
    if ((this.__Compiler_13 == null)) { (this.__Compiler_13 = new import10.Compiler()); }
    return this.__Compiler_13;
  }
  get _APP_ID_14():any {
    if ((this.__APP_ID_14 == null)) { (this.__APP_ID_14 = import38._appIdRandomProviderFactory()); }
    return this.__APP_ID_14;
  }
  get _DOCUMENT_15():any {
    if ((this.__DOCUMENT_15 == null)) { (this.__DOCUMENT_15 = import4._document()); }
    return this.__DOCUMENT_15;
  }
  get _HAMMER_GESTURE_CONFIG_16():import11.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_16 == null)) { (this.__HAMMER_GESTURE_CONFIG_16 = new import11.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_16;
  }
  get _EVENT_MANAGER_PLUGINS_17():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_17 == null)) { (this.__EVENT_MANAGER_PLUGINS_17 = [
      new import39.DomEventsPlugin(),
      new import40.KeyEventsPlugin(),
      new import11.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_16)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_17;
  }
  get _EventManager_18():import12.EventManager {
    if ((this.__EventManager_18 == null)) { (this.__EventManager_18 = new import12.EventManager(this._EVENT_MANAGER_PLUGINS_17,this.parent.get(import41.NgZone))); }
    return this.__EventManager_18;
  }
  get _DomSharedStylesHost_19():import13.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_19 == null)) { (this.__DomSharedStylesHost_19 = new import13.DomSharedStylesHost(this._DOCUMENT_15)); }
    return this.__DomSharedStylesHost_19;
  }
  get _AnimationDriver_20():any {
    if ((this.__AnimationDriver_20 == null)) { (this.__AnimationDriver_20 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_20;
  }
  get _DomRootRenderer_21():import14.DomRootRenderer_ {
    if ((this.__DomRootRenderer_21 == null)) { (this.__DomRootRenderer_21 = new import14.DomRootRenderer_(this._DOCUMENT_15,this._EventManager_18,this._DomSharedStylesHost_19,this._AnimationDriver_20,this._APP_ID_14)); }
    return this.__DomRootRenderer_21;
  }
  get _RootRenderer_22():any {
    if ((this.__RootRenderer_22 == null)) { (this.__RootRenderer_22 = import42._createConditionalRootRenderer(this._DomRootRenderer_21,this.parent.get(import42.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_22;
  }
  get _DomSanitizer_23():import15.DomSanitizerImpl {
    if ((this.__DomSanitizer_23 == null)) { (this.__DomSanitizer_23 = new import15.DomSanitizerImpl()); }
    return this.__DomSanitizer_23;
  }
  get _Sanitizer_24():any {
    if ((this.__Sanitizer_24 == null)) { (this.__Sanitizer_24 = this._DomSanitizer_23); }
    return this.__Sanitizer_24;
  }
  get _ViewUtils_25():import16.ViewUtils {
    if ((this.__ViewUtils_25 == null)) { (this.__ViewUtils_25 = new import16.ViewUtils(this._RootRenderer_22,this._Sanitizer_24)); }
    return this.__ViewUtils_25;
  }
  get _IterableDiffers_26():any {
    if ((this.__IterableDiffers_26 == null)) { (this.__IterableDiffers_26 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_26;
  }
  get _KeyValueDiffers_27():any {
    if ((this.__KeyValueDiffers_27 == null)) { (this.__KeyValueDiffers_27 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_27;
  }
  get _SharedStylesHost_28():any {
    if ((this.__SharedStylesHost_28 == null)) { (this.__SharedStylesHost_28 = this._DomSharedStylesHost_19); }
    return this.__SharedStylesHost_28;
  }
  get _Title_29():import17.Title {
    if ((this.__Title_29 == null)) { (this.__Title_29 = new import17.Title()); }
    return this.__Title_29;
  }
  get _ROUTER_CONFIGURATION_30():any {
    if ((this.__ROUTER_CONFIGURATION_30 == null)) { (this.__ROUTER_CONFIGURATION_30 = {}); }
    return this.__ROUTER_CONFIGURATION_30;
  }
  get _LocationStrategy_31():any {
    if ((this.__LocationStrategy_31 == null)) { (this.__LocationStrategy_31 = import5.provideLocationStrategy(this.parent.get(import43.PlatformLocation),this.parent.get(import44.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_30)); }
    return this.__LocationStrategy_31;
  }
  get _Location_32():import18.Location {
    if ((this.__Location_32 == null)) { (this.__Location_32 = new import18.Location(this._LocationStrategy_31)); }
    return this.__Location_32;
  }
  get _UrlSerializer_33():import19.DefaultUrlSerializer {
    if ((this.__UrlSerializer_33 == null)) { (this.__UrlSerializer_33 = new import19.DefaultUrlSerializer()); }
    return this.__UrlSerializer_33;
  }
  get _RouterOutletMap_34():import20.RouterOutletMap {
    if ((this.__RouterOutletMap_34 == null)) { (this.__RouterOutletMap_34 = new import20.RouterOutletMap()); }
    return this.__RouterOutletMap_34;
  }
  get _NgModuleFactoryLoader_35():import21.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_35 == null)) { (this.__NgModuleFactoryLoader_35 = new import21.SystemJsNgModuleLoader(this._Compiler_13,this.parent.get(import21.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_35;
  }
  get _ROUTES_36():any[] {
      if ((this.__ROUTES_36 == null)) { (this.__ROUTES_36 = [[
        {
          path: '',
          component: import45.HomeComponent
        }
        ,
        {
          path: 'home',
          component: import45.HomeComponent
        }
        ,
        {
          path: 'insight',
          component: import46.InsightComponent,
          data: {meta: {title: 'Insight'}}
        }
        ,
        {
          path: 'pricing',
          component: import47.PricingComponent,
            data: {meta: {
              title: 'Pricing',
              description: 'Slamby pricing, on-premise, SaaS, core-based, open-source.'
            }
          }
        }
        ,
        {
          path: '404',
          component: import48.NotFoundPageComponent,
            data: {meta: {
              title: 'Page not found',
              description: 'The requested page is not found.'
            }
          }
        }
        ,
        {
          path: 'thank-you',
          component: import49.ThankYouComponent,
          data: {meta: {title: 'Thank You'}}
        }
        ,
        {
          path: 'getting-started',
          component: import50.GettingStartedComponent,
            data: {meta: {
              title: 'Getting started',
              description: 'Quick tutorial about Slamby install steps, pricing, licenses, support, SDKs, related softwares and Slamby Insight.'
            }
          }
        }
        ,
        {
          path: 'partners',
          component: import51.PartnersComponent,
            data: {meta: {
              title: 'Partners',
              description: 'Slamby partners who helped a lot to us.'
            }
          }
        }
        ,
        {
          path: 'company',
          component: import52.CompanyComponent,
            data: {meta: {
              title: 'Company',
              description: 'We love what we do, if you need more information about Slamby, just contact us anytime at hello@slamby.com'
            }
          }
        }
        ,
        {
          path: 'legal/privacy-policy',
          component: import53.PrivacyPolicyComponent,
          data: {meta: {title: 'Privacy policy'}}
        }
        ,
        {
          path: 'legal/commercial-license',
          component: import54.CommercialLicenseComponent,
          data: {meta: {title: 'Commercial license'}}
        }
        ,
        {
          path: 'legal/commercial-license-oem',
          component: import55.CommercialLicenseOemComponent,
          data: {meta: {title: 'Commercial license for OEMs'}}
        }
        ,
        {
          path: 'legal/gnu-agpl-license',
          component: import56.GnuAgplLicenseComponent,
          data: {meta: {title: 'GNU AGPL V3 license'}}
        }
        ,
        {
          path: 'legal/open-source-license',
          component: import57.OpenSourceLicenseComponent,
          data: {meta: {title: 'Open-source license'}}
        }
        ,
        {
          path: 'support',
          component: import58.SupportComponent,
          data: {meta: {title: 'Support'}}
        }
        ,
        {
          path: '**',
          redirectTo: '/404'
        }

      ]
    ]); }
    return this.__ROUTES_36;
  }
  get _Router_37():any {
    if ((this.__Router_37 == null)) { (this.__Router_37 = import5.setupRouter(this._ApplicationRef_12,this._UrlSerializer_33,this._RouterOutletMap_34,this._Location_32,this,this._NgModuleFactoryLoader_35,this._Compiler_13,this._ROUTES_36,this._ROUTER_CONFIGURATION_30)); }
    return this.__Router_37;
  }
  get _ActivatedRoute_38():any {
    if ((this.__ActivatedRoute_38 == null)) { (this.__ActivatedRoute_38 = import5.rootRoute(this._Router_37)); }
    return this.__ActivatedRoute_38;
  }
  get _APP_BOOTSTRAP_LISTENER_39():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_39 == null)) { (this.__APP_BOOTSTRAP_LISTENER_39 = [import5.initialRouterNavigation(this._Router_37,this._ROUTER_CONFIGURATION_30)]); }
    return this.__APP_BOOTSTRAP_LISTENER_39;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ROUTER_FORROOT_GUARD_3 = import5.provideForRootGuard(this.parent.get(import59.Router,(null as any)));
    this._RouterModule_4 = new import5.RouterModule(this._ROUTER_FORROOT_GUARD_3);
    this._AppModule_5 = new import1.AppModule();
    this._ErrorHandler_8 = import4.errorHandler();
    this._ApplicationInitStatus_9 = new import7.ApplicationInitStatus(this.parent.get(import7.APP_INITIALIZER,(null as any)));
    this._Testability_10 = new import8.Testability(this.parent.get(import41.NgZone));
    this._ApplicationRef__11 = new import9.ApplicationRef_(this.parent.get(import41.NgZone),this.parent.get(import60.Console),this,this._ErrorHandler_8,this,this._ApplicationInitStatus_9,this.parent.get(import8.TestabilityRegistry,(null as any)),this._Testability_10);
    return this._AppModule_5;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_3; }
    if ((token === import5.RouterModule)) { return this._RouterModule_4; }
    if ((token === import1.AppModule)) { return this._AppModule_5; }
    if ((token === import61.LOCALE_ID)) { return this._LOCALE_ID_6; }
    if ((token === import6.NgLocalization)) { return this._NgLocalization_7; }
    if ((token === import62.ErrorHandler)) { return this._ErrorHandler_8; }
    if ((token === import7.ApplicationInitStatus)) { return this._ApplicationInitStatus_9; }
    if ((token === import8.Testability)) { return this._Testability_10; }
    if ((token === import9.ApplicationRef_)) { return this._ApplicationRef__11; }
    if ((token === import9.ApplicationRef)) { return this._ApplicationRef_12; }
    if ((token === import10.Compiler)) { return this._Compiler_13; }
    if ((token === import38.APP_ID)) { return this._APP_ID_14; }
    if ((token === import63.DOCUMENT)) { return this._DOCUMENT_15; }
    if ((token === import11.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_16; }
    if ((token === import12.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_17; }
    if ((token === import12.EventManager)) { return this._EventManager_18; }
    if ((token === import13.DomSharedStylesHost)) { return this._DomSharedStylesHost_19; }
    if ((token === import64.AnimationDriver)) { return this._AnimationDriver_20; }
    if ((token === import14.DomRootRenderer)) { return this._DomRootRenderer_21; }
    if ((token === import65.RootRenderer)) { return this._RootRenderer_22; }
    if ((token === import15.DomSanitizer)) { return this._DomSanitizer_23; }
    if ((token === import66.Sanitizer)) { return this._Sanitizer_24; }
    if ((token === import16.ViewUtils)) { return this._ViewUtils_25; }
    if ((token === import67.IterableDiffers)) { return this._IterableDiffers_26; }
    if ((token === import68.KeyValueDiffers)) { return this._KeyValueDiffers_27; }
    if ((token === import13.SharedStylesHost)) { return this._SharedStylesHost_28; }
    if ((token === import17.Title)) { return this._Title_29; }
    if ((token === import5.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_30; }
    if ((token === import44.LocationStrategy)) { return this._LocationStrategy_31; }
    if ((token === import18.Location)) { return this._Location_32; }
    if ((token === import19.UrlSerializer)) { return this._UrlSerializer_33; }
    if ((token === import20.RouterOutletMap)) { return this._RouterOutletMap_34; }
    if ((token === import69.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_35; }
    if ((token === import70.ROUTES)) { return this._ROUTES_36; }
    if ((token === import59.Router)) { return this._Router_37; }
    if ((token === import71.ActivatedRoute)) { return this._ActivatedRoute_38; }
    if ((token === import38.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_39; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__11.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);