/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['section.qa[_ngcontent-%COMP%]   .item[_ngcontent-%COMP%]{position:relative;min-height:1px;padding-left:15px;padding-right:15px}@media (min-width: 992px){section.qa[_ngcontent-%COMP%]   .item[_ngcontent-%COMP%]{float:left;width:50%}}'];