/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.item[_ngcontent-%COMP%]{position:relative;float:left;width:100%;min-height:1px;padding-left:15px;padding-right:15px;position:relative;min-height:1px;padding-left:15px;padding-right:15px;position:relative;min-height:1px;padding-left:15px;padding-right:15px;padding:30px}@media (min-width: 768px){.item[_ngcontent-%COMP%]{float:left;width:50%}}@media (min-width: 992px){.item[_ngcontent-%COMP%]{float:left;width:25%}}'];